### ISSUE TITLE
Duplicated lines

### ISSUE THREAD

**Issue by petsuter** [zarunbal/LogExpert#10]
I just upgraded to 1.6.4 and now the following happens:

1. Open file in LogExpert (by double-clicking the file in Windows Explorer)
2. Result: It seems to load correctly.
3. Wait a few (~13) seconds without doing anything.
4. Problem: Suddenly it switches to only showing one line duplicated over and over. Scrolling down to line 500, it switches to a different line duplicated over and over, and so on.

**Comment by petsuter** [comment]
(The file is ~9MB, 100'000 lines long and a few lines are appended every few seconds.)

**Comment by zarunbal** [comment]
@petsuter could you please give me to following points some infos:
- have you many Hilightings / Triggers / Filterings / Filtered to Tab / ... configured
- Which columnizer
- Is the File on a UNC path (like fileserver or something) or local
- If there are lines appended is there a full lock on this file (so that other processes are not allowed to read the file)?
- What have you configured in Options -> Settings .... -> Memory / CPU?

**Comment by zarunbal** [comment]
@petsuter  I have managed to reproduce the problem.

**Comment by petsuter** [comment]
Thanks for investigating.

* I have not changed any configurations from the default. No highlighting, no trigger, no filter.
* I don't know what a columnizer is. The default?
* The file is a local.
* I'm not sure, I think there is a write lock, but reading should be allowed.
* I have not changed any Options / Settings from the default.

**Comment by zarunbal** [comment]
@petsuter There is a new Release which should fix your problem. Could you please test it if this fixes your problem

**Comment by petsuter** [comment]
Thanks for the fix & release. Yes, in a quick test the problem appears to be gone. (Opening the log file in 1.6.4 the problem appears after a few seconds. Opening the same log file in 1.6.6 I did not encounter the problem so far.) I'll switch to 1.6.6 and report back if the problem appears again.

Thanks again

**Comment by zarunbal** [comment]
Thanks for your feedback. I'll close this issue, if this issue appears again feel free to reopen this issue.
