### ISSUE TITLE
Opening files over network bug

### ISSUE THREAD

**Issue by albyrus** [zarunbal/LogExpert#105]
# Bug
If I open log files over network it shows me weird symbols

Tried open files using \\<machineName>\c$\<fileName.log> and mapping a network location as drive. 
Everything works the same:
![image](https://user-images.githubusercontent.com/50635248/57720606-6d489000-763f-11e9-93c0-f91c80d2d57d.png)

LogExpert v 1.7.0

**Comment by zarunbal** [comment]
Could you please check under "View/Navigate -> Encoding" if the Encoding matches your file. Maybe you need to change it.
![2019-05-14 23_45_04-](https://user-images.githubusercontent.com/1749893/57734649-9e0de100-76a2-11e9-911a-a7f692e0c179.png)

**Comment by albyrus** [comment]
That was an issue. For some reason encoding is recognized if file is local, but it doesn't work properly if the same file is opened via network.

I feel bad I didn't try that one :-)
Thank you very much.

**Comment by zarunbal** [comment]
Thank you for your feedback. I'll close this. If you have a problem feel free to open a new issue or reopen this one
