### ISSUE TITLE
ArgumentException on Alt+Tab (while debugging)

### ISSUE THREAD

**Issue by Ryuichiro** [zarunbal/LogExpert#110]
# Bug
When I press Alt+Tab to switch from LogExplorer to another Application while debugging I sometimes get an ArgumentException.
![image](https://user-images.githubusercontent.com/4333206/58106320-799c9200-7bd7-11e9-8ea4-aa657e5ebcfc.png)

Info
- **LogExpert Version:** 1.7
- **Windows Version:** Windows 10 Home (1809)
- **Log file source:** Local files of various file size (~20mb when I decided to report it)
- **Used Columnizer:** my own (https://github.com/Ryuichiro/LogExpert/pull/1)

**Comment by Hirogen** [comment]
yes, this happens becaues the window is not displayed and c# can't draw the lines.

I will close the issue, since this only happens when working with the source code
