### ISSUE TITLE
List of Plugins (Columnizers)

### ISSUE THREAD

**Issue by Myster** [zarunbal/LogExpert#111]
Hi, 
Thanks for the awesome tool.
Is there a list of plugins (Columnizers)?
If so, I think it would be good to have them listed in the wiki pages somewhere.

Cheers.
Murray.

**Comment by Hirogen** [comment]
don't think so

![image](https://user-images.githubusercontent.com/8225398/58807801-10763f00-8619-11e9-8fa6-6fdfa1abb21d.png)

**Comment by Myster** [comment]
Where do I download these?

**Comment by zarunbal** [comment]
The plugins should be already included. It could be possible that there is a problem loading them. You could have a look into [FAQ](https://github.com/zarunbal/LogExpert/wiki/FAQ#error-during-load-of-plugins) or #55. Maybe there is a error logged into the log file (see log file location in [FAQ](https://github.com/zarunbal/LogExpert/wiki/FAQ#logging))

**Comment by Myster** [comment]
That was it, I had to unblock the DLLs.
Cheers.
