### ISSUE TITLE
Installation via Choco for 1.7 is not working any more

### ISSUE THREAD

**Issue by spacemanspiff2007** [zarunbal/LogExpert#114]
Installation via Choco does not work any more. The executables are missing.
See top comment on https://chocolatey.org/packages/logexpert

**Comment by zarunbal** [comment]
Thank you for the issue. I can reproduce the problem

**Comment by zarunbal** [comment]
Fixed with change a8bf36ba8b08c7bd274367f954d1aa2162dbaabf next release should work

**Comment by zarunbal** [comment]
Its released. As soon as it finished automatic moderation review in chocolatey its available. 

I close this issue, if this still is a problem please reopen this issue or create a new issue

**Comment by zarunbal** [comment]
package is approved https://chocolatey.org/packages/logexpert/1.7.1

**Comment by bacar** [comment]
Hi, I can't get any version of a choco install of logexpert to work. It copies the output to the Chocolatey\lib dir but never ends up anywhere else where it might be in the PATH. It doesn't prompt me about running the 'chocolateyInstall.ps1' script like many other packages do so I assume it never actually even attempts to run that?
I tried 1.7.1, 1.8.1, 1.8.2, 1.8.5, 1.8.7 and 1.9.0
