### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by netkhan** [zarunbal/LogExpert#116]
LogWindow.cs has hard-coded for font setting as default.
It would be better to change from Courier New to Consolas for better screen representation.
I could not see why it uses it.

Please let us use better font rendering in output.

**Comment by Hirogen** [comment]
The standard monospaced font is Courier New, this can be seen in the LogWindowPublic.cs

![image](https://user-images.githubusercontent.com/8225398/59415132-32af5000-8dc3-11e9-9ca0-2e497ed6705e.png)

The "NormalFont" and "BoldFont" are based on the preferences set in the settings!

![image](https://user-images.githubusercontent.com/8225398/59414962-e6fca680-8dc2-11e9-888b-b708d0890d8e.png)

Do you have Courier New as Font in the settings configured?

**Comment by Hirogen** [comment]
Courier New is available on all systems, sadly Consolas not, but since anyone can change the font in the settings this issue is closed
