### ISSUE TITLE
Contribute to project

### ISSUE THREAD

**Issue by BestFriend83** [zarunbal/LogExpert#120]
I want to contribute to this project. Is it possible?
I want to add a feature for automatic analyse.
May I create a new branch and create a pull request to the "Development"?

**Comment by zarunbal** [comment]
Sure! always welcome contributions

Just some ideas for your contribution or how it would be great
- Add Unit tests for your contribution
- If possible create it as plugin (maybe it is needed to create a new Plugin interface for you)
- Or make it possible to deactivate / activate the plugin

Just clone the Repository and develop in a branch and create a pull request

I'm keen to see how your automatic analyse works
