### ISSUE TITLE
RegEx Columnizer for Monolog

### ISSUE THREAD

**Issue by arueckauer** [zarunbal/LogExpert#125]
I am trying to create a regex matching log files produced by [Monolog](https://seldaek.github.io/monolog/).

### Log Structure

This is an example log file:

```
[2019-08-08 04:58:19] queue.DEBUG: Counting sheep [] []
[2019-08-08 07:43:51] import.INFO: Collecting data [] []
[2019-08-08 08:15:01] app.WARNING: Lost track of user [4276c94f-b314-11e9-ac2e-00155db728f4] []
```

### Column Definition (expected result)

I would like to have the following columns

- Date
- Time
- Channel
- Severity
- Message
- Context
- Else (the last opening and closing square brackets are not used in my case)

### Regex

This is the regular expression I created.

```
(?<date>[\d{4}-\d{2}-\d{2}\s) (?<time>\d{2}:\d{2}:\d{2}]) (?<channel>.*\.) (?<severity>.*\:) \[(?<message>.*)\] \[(?<context>.*)\] 
```

### Actual result

LogExpert shows one column. The regex is obviously not working. What would the correct regex look like? I appreciate even a hint into the right direction. Thank you!

I am using LogExpert Version **1.8.0** on **Windows 10 Pro 1903**.

**Comment by Hirogen** [comment]
Well this is not a Regex Help Center,

but here are a few things I checked with regexr.com

First you didn't escape the [ so the [ and ] becomes a set, this does not work with your setup you have to escape them like this \[
then you match the \s (whitespace), but you also have a whitespace extra in your regex, so you match it twice!

Here the regex to match the date and time (without the naming)
(\[\d{4}-\d{2}-\d{2}\s(\d{2}:\d{2}:\d{2}\]))

Next, you match severity and message, again, you add spaces between the matching groups, don't do that, a regex is a literal, a whitespace is a whitespace, that will be matched!

here is channel and severity
\s(.*\.)(.*:)

Now is something strange, you have text and [] []
is the text part of one of the [] or is it just some text.

The last part gets weird, you get all kinds of outcomes

Here is my complete Regex... but again, this is not a Regex-Help Group ;)
\[(\d{4}-\d{2}-\d{2})\s(\d{2}:\d{2}:\d{2})\]\s(.*)\.(.*):\s(.+)\s\[(.*)\]\s\[(.*)\]

and with naming
\[(?<date>\d{4}-\d{2}-\d{2})\s(?<time>\d{2}:\d{2}:\d{2})\]\s(?<channel>.*)\.(?<severity>.*):\s(.+)\s\[(?<message>.*)\]\s\[(?<context>.*)\]

**Comment by miltob** [comment]
Hi @arueckauer ,
Not sure if you solved your problem. If not, you may take a look at this issue below:
https://github.com/zarunbal/LogExpert/issues/128#issuecomment-543740248

If you believe you are having the same issue, the fix has been make in a PR and will be available in next release.
