### ISSUE TITLE
json line log

### ISSUE THREAD

**Issue by hilsonp** [zarunbal/LogExpert#13]
Hello,

I'm using LogExpert for quite some time.
Now, my company want to write the logs in a "json line" format.

Would you have an example of Columnizer (code/bin) that would efficiently deal with json format like the 2 log lines below?

{"ts":"2017-11-09 11:20:54,018Z","level":"INFO","msg":"Starting AssetApplication v0.5.51 on 49723547f7f3 with PID 1 (/asset.jar started by root in /)","host":"49723547f7f3","app":"PhAsset","item":"com.asset.AssetApplication","pid":"1","tid":"main"}
{"ts":"2017-11-09 11:20:54,336Z","level":"DEBUG","msg":"Running with Spring Boot v1.5.2.RELEASE, Spring v4.3.7.RELEASE","host":"49723547f7f3","app":"PhAsset","item":"com.asset.AssetApplication","pid":"1","tid":"main"}

Thank you in advance.

Pierre

**Comment by zorglups** [comment]
Thank you.
If we implement it, I will let you know.

**Comment by zarunbal** [comment]
I'm really looking forward to hear how it worked for you

**Comment by zorglups** [comment]
For the record (and for my colleagues) columniser samples can be found here:
https://logexpert.codeplex.com/wikipage?title=Columnizers

@zarunbal : Shouldn't you copy those before CodePlex shuts down?

**Comment by zarunbal** [comment]
I would recommendt to look into the source of this repository and check out DefaultPlugins, CSVColumnizer, GlassfishColumnizer, ... These Plugins are using the new Plugin interface.

The main problem with the old Columnizers is that the Plugin interface is different since [1.6.3](https://github.com/zarunbal/LogExpert/tree/v1.6.3). So they wont work with the current version of LogExpert.

Codeplex has only changed to readonly and will be up some time. The Columnizers linked there are hosted on other servers and not Codeplex.

**Comment by zorglups** [comment]
@zarunbal 
Thanks.

**Comment by louisledev** [comment]
Hi,
I am trying to help zorglups but pretty hard to find out relevant documentation.
I have created a library project targeting .net 4, in there, I have created a class implementing ILogLineColumnizer and the library is referencing ColumnizerLib. 
Do I need to implement the dialog stuff?
How do I import the dlls into LogExpert (there is my dll and newtonsoft.json.dll)?
Thanks.

**Comment by zorglups** [comment]
@zarunbal 
I downloaded the latest version's zip.
The plugin directory contained the CsvColumnizer.dll but it did not appear in the columnizer dropdown.
The same happened for the dll produced by Louis to parse our jsonline files.

We enabled the LogExport logs and opened them (with LogExpert ;-D).

It showed errors saying "An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions ...".

To solve this, we had to do for each columnizer DLL (and their dependency DLLs):

1. Right Click the dll
2. Click Properties
3. Click Unblock

![image](https://user-images.githubusercontent.com/7338241/33487162-a583a614-d6ac-11e7-8c52-f900fc6cd4f0.png)

I read that this can be done on the zip file itself and all files inside get trusted.
Is there anything you can do at your side to make the DLL's you deliver, trusted automatically?

If no, or "no time", I think it is worth a note in the wiki and/or a readme.txt in the plugin folder.

What do you think ?

**Comment by zarunbal** [comment]
@louisledev I'll write a short Wiki entry which describes how to get it working. I hope that I have time this weekend.

@zorglups this problem seems related to #8 . Have you downloaded the files with Internet Explorer or extracted the zip with the Windows Explorer? What OS do you have? There is currently a workaround mentioned in the related issue.

**Comment by louisledev** [comment]
@zarunbal  I managed to get our columnizer working. It would still be great to have a wiki though!
Thanks. 

![image](https://user-images.githubusercontent.com/7973386/33505250-f4988a38-d6ea-11e7-84da-5f2ec7ad84a7.png)

**Comment by zarunbal** [comment]
I have started to write a wiki entries for the [Plugins](https://github.com/zarunbal/LogExpert/wiki/Plugins). There are some Informations but that have to be extendended and maybe I have to change the Layout. I'm currently not satisfied with the entries.

@louisledev congratulations for the running plugin

**Comment by louisledev** [comment]
@zarunbal thank you for the wiki. What I could not figure out was the use of the ILogLineColumnizerCallback callback in some calls. Any info on this? (in my case, I end up parsing twice the log line, for the timestamp and for the split, so wondering if I could use it for this use case).
Also, wewould like to let the user configure the columnizer, what do we need to implement to provide some configuration? In the UI, there is a config button but greyed in my case:
![logexpert](https://user-images.githubusercontent.com/7973386/33561205-5852daf0-d912-11e7-94cf-086286333b6c.jpg)
Any hint? thanks.

**Comment by zarunbal** [comment]
Yes with TimeShift enabled, you (sadly) must parse twice the LogLine.

# ILogLineColumnizerCallback:
This is for some really special cases in where you need additional infos about the LogFile or get specific lines. Most of the time you can ignore this parameter.

# Configuration
Implement the `IColumnizerConfigurator` Interface in your columnizer.

## Methods
**Configure**
This is called when the user clicks on the "Config" button. There you can show a Dialog. You have to implement the whole logic of handling Save/Cancel/store of settings by yourself. 

**Load**
Called after the columnizer is loaded from LogExpert. Load there your saved configuration and maybe if there is no config some defaults.

## Example
https://github.com/zarunbal/LogExpert/blob/master/src/CsvColumnizer/CsvColumnizer.cs

**Comment by miltob** [comment]
@zorglups , I did some changes for json files in earlier versions.
For the sample lines you put here, now it looks like below:
![image](https://user-images.githubusercontent.com/42666057/57699103-7b77ca00-769a-11e9-9150-9e009301734c.png)
Not sure if this is what you need. Feel free to put comment here. 
If that's what you need, we could close this ticket now.

**Comment by Hirogen** [comment]
there are now two JSON Columnizer (Version 1.8.7) that can parse logs in json format, please check them out and see if they fit.
