### ISSUE TITLE
LogExpert has stopped working

### ISSUE THREAD

**Issue by Shawnaanand** [zarunbal/LogExpert#131]
LogExpert  has stopped working. am getting this error while running, please help how to resolve this thanks
Problem Signature:
Problem Event Name: APPCRASH

Fault Module Name : gdiplus.dll

![Uploading log
![logexpert issue](https://user-images.githubusercontent.com/46771718/64874537-d8938480-d668-11e9-8cca-0a6ecdc2b59f.png)
expert issue.png…]()

**Comment by Shawnaanand** [comment]
Sorry , now attached with picture , for some reason it didn’t upload last time, log expert working fine without crash in my system . When some users remote login it crashes with below pop up screen , not sure what GDIPLUS.dll error. Please help. Thanks
Windows server 2012R2 64 bit
Logexpert version 1.6

[
![9A83FB2E-FC13-4DC5-BF51-2747C642BC10](https://user-images.githubusercontent.com/46771718/65006721-8b8e0780-d921-11e9-8e3c-f808caf355c7.jpeg)
](url)

**Comment by zarunbal** [comment]
Please upgrade to the latest version of LogExpoert 1.6.0 is really old. I'll close this issue, if this error is still persists in the new version, feel free to reopen this bug. (If you have to reopen the Bug please check out the [Wiki](https://github.com/zarunbal/LogExpert/wiki/FAQ#event-log) and extract from there the detailed informations about the crash from the eventlog)
