### ISSUE TITLE
Pressing F3 twice generates an exception

### ISSUE THREAD

**Issue by LouisPhilippeEpic** [zarunbal/LogExpert#132]
# Bug
When I press F3 to search for the next match it seems to work only once.

On the second press I always get this exception:

> Operation is not supported when VirtualMode is set to true.
> 
> 
> InvalidOperationException
>    at System.Windows.Forms.DataGridView.Sort(DataGridViewColumn dataGridViewColumn, ListSortDirection direction)
>    at System.Windows.Forms.DataGridView.ProcessF3Key(Keys keyData)
>    at System.Windows.Forms.DataGridView.ProcessDataGridViewKey(KeyEventArgs e)
>    at System.Windows.Forms.DataGridView.OnKeyDown(KeyEventArgs e)
>    at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
>    at System.Windows.Forms.DataGridView.ProcessKeyEventArgs(Message& m)
>    at System.Windows.Forms.Control.WmKeyChar(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Hirogen** [comment]
What Version are you using? I can't reproduce the behaviour in 1.8.0, 
Pressing F3 multiple times works fine in 1.8.0.

**Comment by shay-shilo** [comment]
I'm also having this issue. 

### Additional info:
- Happens with 1.8.0 (compiled, debug, VS2019), 1.8.1 (compiled, debug, VS2019) and with 1.8.1 exe downloaded from the releases in Git.
- I tried several types of files with different contents (short lines, very long lines)
- I always tested with English text
- Sometimes you can press F3 a few times and it'll work but it'll fail at some point, perhaps when the search rolls back? I'm not sure.
- PC: Windows 10 Enterprise x64 V1803 OS build 17134.885

**Comment by LouisPhilippeEpic** [comment]
Hi! I'm getting this on 1.8.0 downloaded from github

PC: Windows 10 enterprise V1709 OS Build 16299.1331

**Comment by Pr0metheus2** [comment]
Same issue. Ver. 1.8.1

**Comment by Pr0metheus2** [comment]
No issue in v.1.7.1.

**Comment by zarunbal** [comment]
I can reproduce it. Just open e.g. the LogExpert log and search for ```|``` then I just have to hit F3 and I get the exception.

**Comment by zarunbal** [comment]
Please test the new release. Please provide a short feedback

**Comment by LouisPhilippeEpic** [comment]
Confirming fixed in 1.8.2

Thank you very much!
