### ISSUE TITLE
How to add alert info LogExpert

### ISSUE THREAD

**Issue by gills0105** [zarunbal/LogExpert#133]
# Question
I want to add alert sound for some Highlighting lines. Is it possible?

**Comment by Hirogen** [comment]
Currently not, this is a feature request

**Comment by zarunbal** [comment]
You could activate in "Hilighting and action triggers" the plugin ProcessLauncher and then start some player with a specified sound file
![processLaunch](https://user-images.githubusercontent.com/1749893/65255307-f136eb00-dafd-11e9-9b2a-377b8ece0dc1.png)

Please provide a short feedback if this helped you and in case close this issue

**Comment by gills0105** [comment]
> You could activate in "Hilighting and action triggers" the plugin ProcessLauncher and then start some player with a specified sound file
> ![processLaunch](https://user-images.githubusercontent.com/1749893/65255307-f136eb00-dafd-11e9-9b2a-377b8ece0dc1.png)
> 
> Please provide a short feedback if this helped you and in case close this issue

Sorry for my late reply.
I have tried to  use LogExpert 1.8 and follow you tip. However, the combobox is empty, I cannot select plugin ProcessLauncher.
![image](https://user-images.githubusercontent.com/55486206/65495641-ac3dfa80-dee9-11e9-9e95-fd417ddcb09e.png)
After typing the sound player with a specified sound file and click OK, an exception occurs:
![image](https://user-images.githubusercontent.com/55486206/65495929-1fe00780-deea-11e9-9d65-c1cbda32a1aa.png)

How to solve this problem?

Many Thanks.

**Comment by zarunbal** [comment]
Could you check if the file ```Plugins/DefaultPlugins.dll``` is blocked by windows? How did you install LogExpert? You can also check [wiki](https://github.com/zarunbal/LogExpert/wiki/FAQ#error-during-load-of-plugins) or #55 maybe this helps

**Comment by gills0105** [comment]
Hello, I have built LogExpert by myself and plugin can be loaded finally! Thank for your help.
