### ISSUE TITLE
Sftp doesn't work

### ISSUE THREAD

**Issue by uzijazi** [zarunbal/LogExpert#134]
# Bug
Sftp does not work, because ChilkatDotNet47 is not recognized or is present in the wrong version.

Important questions
- LogExpert Version = 1.8.1
- Windows Version = Windows 10 x64 1903
- Used Columnizer = none
- Is this version specific or a new problem = first tried in 1.8.1

#General 
After unzipping the LogExpert zip file and double click the logexpert.exe, I tried to open an Sftp-Url to one of our servers. We received the dialog windows (screenshot). In the LogExpert-Logfile we get the following error (german version):

```
2019-09-28 18:19:05.7354|INFO|Program|
============================================================================
LogExpert 1.8.1 started.
============================================================================
2019-09-28 18:19:13.1345|ERROR|LogExpert.FileSystemCallback+NLogLogExpertWrapper|Die Datei oder Assembly "ChilkatDotNet47, Version=9.5.0.72, Culture=neutral, PublicKeyToken=eb5fc1fc52ef09bd" oder eine Abhängigkeit davon wurde nicht gefunden. Es wurde versucht, eine Datei mit einem falschen Format zu laden.
2019-09-28 18:19:13.1345|ERROR|LogExpert.LogWindow|LogExpert.LogFileException: Cannot find sftp://server.domain.int/file.xml
   bei LogExpert.LogfileReader.GetLogFileInfo(String fileNameOrUri)
   bei LogExpert.LogfileReader.AddFile(String fileName)
   bei LogExpert.LogfileReader..ctor(String fileName, EncodingOptions encodingOptions, Boolean multiFile, Int32 bufferCount, Int32 linesPerBuffer, MultifileOptions mutlifileOptions)
   bei LogExpert.LogWindow.LoadFile(String fileName, EncodingOptions encodingOptions)Cannot find sftp://server.domain.int/file.xml LogExpert.LogFileException LogExpert.LogFileException: Cannot find sftp://server.domain.int/file.xml
   bei LogExpert.LogfileReader.GetLogFileInfo(String fileNameOrUri)
   bei LogExpert.LogfileReader.AddFile(String fileName)
   bei LogExpert.LogfileReader..ctor(String fileName, EncodingOptions encodingOptions, Boolean multiFile, Int32 bufferCount, Int32 linesPerBuffer, MultifileOptions mutlifileOptions)
   bei LogExpert.LogWindow.LoadFile(String fileName, EncodingOptions encodingOptions)

```
The server is reachable with ssh, scp and sftp (Putty, WinSCP etc.), so we think the problem is the missing or wrong ChillKatDotNet.

![Anmerkung 2019-10-01 113752](https://user-images.githubusercontent.com/47883535/65951225-ee15f600-e43f-11e9-8b29-0b2c0517ab6c.png)

**Comment by zarunbal** [comment]
You are right, the Chillkatdotnet is missing.

**Comment by zarunbal** [comment]
can you please test the new release if it works for you? Please give a short feedback if it is working

**Comment by uzijazi** [comment]
Now the ChilkatDotNet47.dll isn't missing anymore. So it works.
