### ISSUE TITLE
Add possibility to label RegEx columnizer to ease switching

### ISSUE THREAD

**Issue by arnaudjolly** [zarunbal/LogExpert#148]
# Feature
Is it possible to put some labels on custom RegEx columnizer instead of RegEx1..N ?

I work on different projects that are using different specific log formats.
But when I want to select the correct custom RegEx columnizer, I have to remember which number fits the file.

Thanks for your time and efforts!

**Comment by zarunbal** [comment]
This is now implemented in the new release. 

The feature has some limits! 
- After renaming a Regex columnizer you have to restart LogExpert to refresh everywhere the name
- If you change the name of a Regex columnizer the assignment in the Settings -> Columnizers is lost!

This are the current limits I stumpled upon testing

Feel free to send any feedback / suggestions
