### ISSUE TITLE
Settings > Columnizer selection

### ISSUE THREAD

**Issue by arnaudjolly** [zarunbal/LogExpert#149]
# Bug
When configuring Columnizer to use per file mask, selection for RegEx Columnizers are all named the same: `Regex`.
It's not practical when returning to this config screen to find which regex is used.

Important questions
- LogExpert Version: **1.8.2**
- Windows Version: **Microsoft Windows 10 Professionnel**
- Lokal file or Network: **Local**
- Used Columnizer: **RegEx**
- Is this version specific or a new problem: **was present before**

Optional questions(depends on the problem):
- Screenshot: ![image](https://user-images.githubusercontent.com/1591785/72162098-99303700-33c1-11ea-8808-51424dbb4112.png)

Thanks for your time and efforts.

**Comment by zarunbal** [comment]
This is fixed in the new release. If you still encounter the problem feel free to reopen the issue
