### ISSUE TITLE
Reading CSV comma delimited

### ISSUE THREAD

**Issue by eliassal** [zarunbal/LogExpert#150]
Ihave a very basic question: Can this tool read correctly CSV files generated by Syslog? I importe one CSV file, it displays each single line in one big cell in spite of the fact that there is a comma delimited fields as follows

> Information,System,2020/01/15 09:33:12,SYSTEM,System started to boot up.

**Comment by Hirogen** [comment]
Try the csvColumnizer.CsvColumnizer in the Columnizer Options


![image](https://user-images.githubusercontent.com/8225398/72728229-28d9a080-3b8d-11ea-8970-20b4fa4d5740.png)

**Comment by zarunbal** [comment]
You have to configure the CSV columnizer. The default delimiter is ; and not , . If you change this it should work as expected

**Comment by eliassal** [comment]
OK, yes it did. Now, I have another log file which is similar to a web log, delimited by spaces as follows

> date time action protocol src-ip dst-ip src-port dst-port size tcpflags tcpsyn tcpack tcpwin icmptype icmpcode info path
> 2020-02-02 18:57:50 DROP UDP 192.168.10.5 224.0.0.251 5353 5353 56 - - - - - - - RECEIVE
> 2020-02-02 18:57:50 DROP UDP fd80::61a7:b4b9:6cc1:ba34 ff02::fb 5353 5353 76 - - - - - - - RECEIVE
> 

I tried weblog but it did not work

**Comment by Hirogen** [comment]
You do realize you can write your own regex-columnizer?

![image](https://user-images.githubusercontent.com/8225398/73955816-42584780-4904-11ea-847c-51e9a9d2cc35.png)

**Comment by eliassal** [comment]
Hirogen, I am not comfortable with RegEx, it will be difficult for me, can you help please Thanks

**Comment by Hirogen** [comment]
> Hirogen, I am not comfortable with RegEx, it will be difficult for me, can you help please Thanks

Well I don't know your protocol and, this is also not a regex-community. And you should really learn how to use them, because, regex are super super usefull.

Based on your 2 examples, here is some rudimentary regex, this might or might not work

(\d{4}-\d{2}-\d{2}) (\d{2}:\d{2}:\d{2}) ([A-Z]{4}) ([A-Z]{3}) (.+) (\d{4}) (\d{4}) (\d{2}) (.+-) (.+)

**Comment by eliassal** [comment]
Thanls Hirogen but it sit did not work as you can notice in the snapshot. But tell me, how do you reach the interface where you cdo config Regex, it seems that my version does not have this
![regexdidnot](https://user-images.githubusercontent.com/8447864/74014922-f0f59a00-498f-11ea-84e7-b31e14ac39f3.jpg)

**Comment by eliassal** [comment]
Hirogen, what option I should use initially

![2020-02-07](https://user-images.githubusercontent.com/8447864/74015215-7ed18500-4990-11ea-931d-96a9ed0c686c.png)

**Comment by Hirogen** [comment]
First thing you should do, is update to the latest version!

The Screenshot looks like a version way before regex filtering was implemented!

This is a screenshot from the latest version
![image](https://user-images.githubusercontent.com/8225398/74031936-0b8d3a80-49b3-11ea-961d-29dbe0ae9767.png)

**Comment by eliassal** [comment]
so many thanks for the hint, downloaded the latest version1.8.5, I entered the regex but it is giving 10 empty columns, when I applu it it dispalys 10 empty column and and 11th one with the whole line
![regexdidnotNVer](https://user-images.githubusercontent.com/8447864/74047816-3e462b80-49d1-11ea-94a3-ac756f58c210.jpg)

![regexdidnotNVer1](https://user-images.githubusercontent.com/8447864/74047894-603fae00-49d1-11ea-9519-6d6cc446dce5.jpg)

**Comment by Hirogen** [comment]
Well I honestly don't know...

It works with both lines on my end, with the regex I provided.
![image](https://user-images.githubusercontent.com/8225398/74217982-4dff9180-4ca9-11ea-832d-ccb31f0c96f5.png)

![image](https://user-images.githubusercontent.com/8225398/74217987-52c44580-4ca9-11ea-9f0a-1417b2ff2ce5.png)


Maybe a copy paste error?


best thing todo is, copy the regex into: https://regexr.com/
And test it with a few lines of your log file!

That's how I do it, and there you can find out what is wrong with the regex on your side

![image](https://user-images.githubusercontent.com/8225398/74218099-9d45c200-4ca9-11ea-9fcf-4587a8711fac.png)

**Comment by zarunbal** [comment]
I changed the regex a bit and now it matches your examples. 
`(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2}:\d{2})\s+([A-Z]+)\s+([A-Z]+)\s+([^\s]+)\s+([^\s]+)\s+(\d+)\s+(\d+)\s+(\d+)\s+([-\s]+)(.+)`
I hope this time it works also on your machine

**Comment by eliassal** [comment]
I tried with your new formula, when I do check I get the right number  of fields but nothing in the fields as follows


![image](https://user-images.githubusercontent.com/8447864/77227253-402e0d80-6b7f-11ea-8f1e-4173bf92da20.png)

Applying it gives the same results as before

![image](https://user-images.githubusercontent.com/8447864/77227275-5b991880-6b7f-11ea-93f3-19d3b3d83015.png)

**Comment by eliassal** [comment]
zarunbal, I applied expressions 1 by one until I reached 

> (\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2}:\d{2})\s+([A-Z]+)\s+([A-Z]+)\s+([^\s]+)\s+([^\s]+)\s+(\d+)\s+(\d+)\s+(\d+)

It worked fine even when applying it
![image](https://user-images.githubusercontent.com/8447864/77227405-6ef8b380-6b80-11ea-9382-fe68622983a4.png)

![image](https://user-images.githubusercontent.com/8447864/77227375-3ce75180-6b80-11ea-94e2-0fb4da81513d.png)

Once I add the last piece

> \s+([-\s]+)(.+)
I get 11 empty boxes

**Comment by eliassal** [comment]
I needed to update the regex as follows, added the text in bold

(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2}:\d{2})\s+([A-Z]+)\s+([A-Z]+)\s+([^\s]+)\s+([^\s]+)\s+(\d+)\s+(\d+)\s+(\d+)**\s+\w**\s+(\d+)\s+(\d+)\s+(\d+)\s+([-\s]+)(.+)

I get good results but the S just behind number 44 is not showing
2020-03-20 23:44:22 DROP TCP 80.82.70.118 192.168.1.34 60000 25 44 **S** 407068240 0 1024 - - - RECEIVE

![image](https://user-images.githubusercontent.com/8447864/77227997-8fc30800-6b84-11ea-8d02-f8f6a210a39f.png)

so I am getting 14 boxes instead of 15 ???
