### ISSUE TITLE
munches lines in very large files

### ISSUE THREAD

**Issue by marcel-landman** [zarunbal/LogExpert#152]
- When viewing a very large file (156Mb) lines dissapear
- the dissapeared lines are replaced with a few garbage characters on one line
- the location of the disappearing lines is consistent for a given file
- the garbage is consistent for the given file
- the line number where the issue occured according to logexpert is 3,373,000
- the actual line number where the issue occured is 3,311,970
- the number of lines munched was 57
- no filter or columnizer in use
- Unfortunately, I cannot share the log file (customer confidential)
- LogExpert Version 1.8.4
- Windows Version 10 Pro
- Lokal file or Network: local
- Is this version specific or a new problem: Don't know, first time user

**Comment by Hirogen** [comment]
what does munches mean, I can not find it in any dictionary??? 

Also this seems odd, I work with 500mb to 2-3gb files and no lines disappear or are replaced as long as they are local-files on the harddisk.

Could you create a Video or screenshots of what is happening?

**Comment by marcel-landman** [comment]
In normal English it means to eat,
https://dictionary.cambridge.org/dictionary/english/munch

But in the context of computer data it usually refers to the unexpected loss of sections of data while leaving other data intact, leaving what reminds one of bite marks.
I'm sorry I cannot share any of the data. It sounds like the file size isn't what is causing the problem.
The only other hint I can give you is that the data is in pretty printed JSON format, so the lines are generally short with indentations. Hope that helps.

________________________________

**Comment by Hirogen** [comment]
hmm, JSON is multiline, so that could be your problem, logexpert probably can't show you the whole JSON because it does not know how to interpret the data and so lines "disappear".

this can also happen with xmls that are multiline

try it with a file, where there is no "pretty printed" json

**Comment by marcel-landman** [comment]
why would logexpert interpret anything? they are just lines. I'm not using columnizer
also, out of 3 million lines only 60k lines were munched. How come the rest was ok?

**Comment by zarunbal** [comment]
Could it be that there were excesive long lines (>20000 characters), which are missing?

**Comment by marcel-landman** [comment]
no, quite the opposite: the lines are unusually short for a log file. Most lines look like this:
            "key": "value",\n

**Comment by Hirogen** [comment]
Yes, but you have probably large JSONs that go over multiple pages, the same happens with xml-strings that have \n and go over multiple pages, those are truncated and you only see the "next" complete line. Though, I haven't seen one of those, since zarunbal took over development, but this could also be, because at my company we try to avoid \n in strings we log, we explicitly wrote string extensions that get rid of those.

**Comment by marcel-landman** [comment]
\n is the newline character how can you avoid that in a log?

**Comment by zarunbal** [comment]
maybe there is something in the reader with the detection of newlines, not that I gets confused by written \n (Literally the two chars, and not the newline character)

**Comment by marcel-landman** [comment]
sorry about that, I intended to clarify not confuse. I meant the new line character, not the litereral string '\n'. I was only telling you this so that you know the file does _not_ contain \n\r but _only_ \n characters. It seems doubtful you will be able to fix this issue without the data so perhaps we should close the issue and wait for someone that has data that can be shared.

**Comment by Hirogen** [comment]
> rry about that, I intended to clarify not confuse. I meant the new line character, not the litereral string '\n'. I was only telling you this so that you know the file does _not_ contain \n\r but _only_ \n characters. It seems doubtful you will be able to fix this issue without the data so perhaps we should close the issue and wait for someone that has data that can be shared.

you can share the data privately, you don't need to post it here, just send zarunbal a private message :)
