### ISSUE TITLE
[feature] time zone convert

### ISSUE THREAD

**Issue by TekBear** [zarunbal/LogExpert#154]
I would really like a log viewer that can be configured to show a log with UTC date time stamps as local date time stamps. For example the "folding at home" software log is UTC but I really just want to view  the log with log times displayed using my local time zone. 

Can this be done currently in logexpert or any other log viewers?

**Comment by Hirogen** [comment]
this feature is currently not supported, it would mean to not only show the log but also interpret the content, this would cost a lot of performance.

I could be done, but this is probably a bigger change.

It would be simpler to read the file and replace all dates with a regex into the format you desire and then open it in logexpert.

**Comment by TekBear** [comment]
> It would be simpler to read the file and replace all dates with a regex into the format you desire and then open it in Logexpert.

It is more than just a regex transformation, as you need to: 
- create an integer time value and 
- add/subtract your time zone offset; and 
- support real time log

How about extending Logexpert's plugin capability by adding a wrapper plugin that calls a user defined script (for example a VBScript) when each real time log data line arrives. The script is passed the log data line as input and  returned transformed data. I can write the user defined VBScript code part.

Examples of API hooks/user exits/plugins found in other software: 

- Bginfo.exe (Microsoft Sysinternals) has hooks for using user defined VBScript (full VB function list, and subset of other features)

- Videolan (VLC) has hooks for calling LUA. 

It Would be nice if wrapper was generic enough to support other script language e.g. LUA, Python, or Perl. I could learn to write the back end code in another language if I have too.
