### ISSUE TITLE
http://www.log-expert.de/ no longer related?

### ISSUE THREAD

**Issue by ansorg** [zarunbal/LogExpert#159]
hi

just installed 1.8.5 and noticed that the "About" screen still points to http://www.log-expert.de/ which has some strange content (as of today) 

![grafik](https://user-images.githubusercontent.com/3541784/80601688-6b353800-8a2e-11ea-953e-e4af0cf54d73.png)

**Comment by solarpolar** [comment]
It means "go away" :(

**Comment by Hirogen** [comment]
see pull request #160 , changed it to the new github url

**Comment by zarunbal** [comment]
See new release, I'll close this issue. If there is still a problem feel free to reopen this issue :)
