### ISSUE TITLE
Blank lines - feature I can turn off? Or bug?

### ISSUE THREAD

**Issue by kingd123** [zarunbal/LogExpert#162]
Hi,

I'm not sure if this is a feature request, or a request to know where the appropriate setting exists. I've drawn a blank after looking through all the documentation, FAQ, etc.

What I'm looking for, is to prevent LogExpert inserting a blank line in the displayed received data. It seems to do this whenever it goes, every 250 ms, to see if there is any more incoming data, but finds there is none. The prevalence of the issue is much reduced if I reduce the file polling interval to 500 ms. But then I can't see my incoming data update as often as I would like.

BareTail, interestingly, doesn't do this with the same incoming data stream.

I'm using LogExpert 1.8.5, the latest presently. My Windows version is Version 10.0.18362.592. 64-bit. Local file. No Columnizer used. I've not used LogExpert before (it probably shows), so i'm unable to say if earlier versions do the same.

The log file is continuous appending, about every 140 ms, althouh that varies between 80 and 300 ms. Alternatively, the log file appends every 250 ms.

All settings at defaults, apart from 6 higlight rules I've added. All just a few characters.

Best regards,

David King

**Comment by Hirogen** [comment]
what do you mean with inserts a line every 250ms? 
You see a blank line? That sounds rather odd, like bug.

**Comment by zarunbal** [comment]
Could it be that the lines are bigger than 20000 characters?

**Comment by kingd123** [comment]
@Hirogen: Yes, if I have LogExpert polling interval set to 250 ms, LE displays a numbered blank whenever it polls for change to my file but finds there is none, seemingly. The same happens if I set the polling interval to 500 ms, or to 1s: Whenever LE polls my file, if no change, LE displays a numbered blank line.

@zarunbal: Nope. My lines vary in length between about 50 and 150 characters.

**Comment by Hirogen** [comment]
> @Hirogen: Yes, if I have LogExpert polling interval set to 250 ms, LE displays a numbered blank line whenever it polls for change to my file but finds there is none, seemingly. The same happens if I set the polling interval to 500 ms, or to 1s: Whenever LE polls my file, if no change, LE displays a numbered blank line.
> 

This is quite interesting, we poll every 250ms as well and our logfiles are usually  500mb+ big and write about 300-400 lines per second, so this might be an issue that the logfile has not been updated in the last 250ms.

**Comment by Hirogen** [comment]
@kingd123 could you test this with version 1.8.7 and see if this is still a problem?

**Comment by kingd123** [comment]
Hi Patrick,

I’m really sorry, but I’ve changed contract job several times, since highlighting the blank line issue. So I now cannot really commit the time to downloading LogExpert version 1.8.7, and setting up the test scenario again, to see if the problem is now. Infact since that contract ended, I no longer have access to the hardware with which LogExpert was used. So I’d have to create an alternative source of data for use with LogExpert. I’m sorry I am unable to help test.

Best regards,

David

**Comment by Hirogen** [comment]
no reproducible
