### ISSUE TITLE
Feature request: Capturing groups in text highlighting

### ISSUE THREAD

**Issue by hakanostrom** [zarunbal/LogExpert#163]
use case:
Using a regex, I want to select text that is preceded by something, without highligting that something.

In short, I want to use a regex with selection groups and be able to define that only a certain selected group should be highlighted. Today the whole match of the regex is highlighted as I understand.

**Comment by natenho** [comment]
@hakanostrom, it is possible to use lookahead and lookbehind RegEx expressions to achieve the result you were looking for.

Example:

Given the following log entries:

```
The quick brown fox jumps over the lazy dog
The quick blue fox jumps over the lazy dog
-
```

If you want to highlight only `brown fox` then you can create the highlight expression as

(?<=brown )fox

![image](https://user-images.githubusercontent.com/4236481/108586411-22d46700-732d-11eb-8a80-8a3a616966a7.png)

**RegEx reference**

`(?=foo)` | **Lookahead** | Asserts that what immediately follows the current position in the string is foo
`(?<=foo) `| **Lookbehind** | Asserts that what immediately precedes the current position in the string is foo
`(?!foo)` | **Negative Lookahead** | Asserts that what immediately follows the current position in the string is not foo
`(?<!foo)` | **Negative Lookbehind** | Asserts that what immediately precedes the current position in the string is not foo

**Comment by Hirogen** [comment]
If this is still a problem after the lookaheads and lookbehinds, please reopen the issue
