### ISSUE TITLE
Bug: typo in Highlighting dialog

### ISSUE THREAD

**Issue by hakanostrom** [zarunbal/LogExpert#164]
In the dialog for highlighting and action triggers there is a typo. It says "Hilighting ..." but the correct word is "Highlighting"

![image](https://user-images.githubusercontent.com/1530531/81472856-cae3ce00-91fa-11ea-89af-de6fc6c03efc.png)

LogExpert version 1.8.5

**Comment by zarunbal** [comment]
Should be fixed in the new release
