### ISSUE TITLE
Menu bar is displayed below the toolbar

### ISSUE THREAD

**Issue by kintrupf** [zarunbal/LogExpert#166]
# Bug
The [Menu bar is displayed below the toolbar](url)

Important questions
- LogExpert Version: 1.8.7
- Windows Version: Windows 10 Build 18363
- Lokal file or Network lokal
- Used Columnizer none
- Is this version specific or a new problem

![2020-05-11 11_07_50-LogExpert](https://user-images.githubusercontent.com/8496344/81544912-664e7d80-9378-11ea-840c-b670ecff8e75.png)

On two on my computers the menu bar is displayed below the toolbar. I can't find an option to change this, nor does a re-install solve the problem.
I've installed Logexpert via chocolatey. On two other computers the menu bar is displayed correctly above the toolbar.

**Comment by zarunbal** [comment]
Thanks for your issue report, the menu and the toolbars are fixed, there is no option / configuration which can change there position.

Do you have the same behavior with previous versions or the same? Do you have a bigger scaling (Display settings Scale) for your display? Or a multi monitor setup with different dpi settings?

**Comment by kintrupf** [comment]
> Do you have the same behavior with previous versions or the same?
First install on both computers with this version. But I'll test some previous versions.

> Do you have a bigger scaling (Display settings Scale) for your display?
One computer has a 4K screen with 125% scaling, the other is a netbook with a rather small screen and definitively without scaling. 

> Or a multi monitor setup with different dpi settings?
The big screen has a secondary monitor without scaling

**Comment by kintrupf** [comment]
I just tried it with version 1.7.1 on one of the computers. Same result, the menu bar is below the toolbar.
Before installation of the old version I deleted the settings folder in %AppData%\LogExpert, so it probably was a clean install.

**Comment by Hirogen** [comment]
> I just tried it with version 1.7.1 on one of the computers. Same result, the menu bar is below the toolbar. Before installation of the old version I deleted the settings folder in %AppData%\LogExpert, so it probably was a clean install.

could you try this with version 1.8.7, this is a quite odd behavior

**Comment by Hirogen** [comment]
This works with 1.8.7, please test with this Version and if it still is a problem, reopen the issue

<img width="503" alt="image" src="https://user-images.githubusercontent.com/8225398/179361461-219d8a97-0c87-4cd8-88df-e9e026a7435a.png">
