### ISSUE TITLE
in PortableMode Columnizer settings still placed in AppData

### ISSUE THREAD

**Issue by Dimentium** [zarunbal/LogExpert#167]
# Bug
From 1.8.7 there is a Portable Mode.
It's great and I like it very much!
But Regex?Columnuizer.xml files still use AppData folder instead executables folder.

Important questions
- LogExpert Version: 1.8.7
- Windows Version: Server 2019 Standart / Win 10 Pro
- Lokal file or Network: local
- Used Columnizer: any

**Comment by zarunbal** [comment]
@Hirogen can you have a look into?

**Comment by Hirogen** [comment]
> @Hirogen can you have a look into?

Yes, will have a look tonight, after work :)

**Comment by Hirogen** [comment]
this is fixed in 1.8.8 https://github.com/zarunbal/LogExpert/pull/234
