### ISSUE TITLE
LogExpert presentation

### ISSUE THREAD

**Issue by hilsonp** [zarunbal/LogExpert#17]
@zarunbal 

I wrote a document to present LogExpert to our support and dev teams.
https://www.dropbox.com/s/ue748uy7wh676zp/LogExpert%20top%2010%20features.zip?dl=0

Please find it attached, would that be useful for the project ;-)

Best regards,

**Comment by zarunbal** [comment]
Amazing, thank you for sharing this document :) I really appreciate this.

@zorglups would it be okay for you if I integrate your document into the Wiki (with some changes but most of the document)

**Comment by zorglups** [comment]
@zarunbal 
Please do whatever you like with this document. It displays much nicely on our wiki but this is the best export I could reach. If you want it in another format, I can see what I can do.
I unfortunately can't code C# so this is pretty the only contribution I can bring to this project.

If you see non-C# areas where I can help you, please tell me. This can be documentation, translation to French, beta testing, trying to reproduce problems, ...

**Comment by zarunbal** [comment]
@zorglups any contribution is appreciated! Most of the documentation is more or less not existant or outdated, so it would be great if there would be more. Even if you proofread the existing pages would be great.
