### ISSUE TITLE
Some text/input is covered

### ISSUE THREAD

**Issue by keai4le** [zarunbal/LogExpert#171]
**[environment]**
Window10 2004

**[Screen shot]**
![image](https://user-images.githubusercontent.com/8185606/83943440-bbbe6300-a82e-11ea-97ef-1edc7b79b651.png)
![image](https://user-images.githubusercontent.com/8185606/83943478-1061de00-a82f-11ea-9911-838cb3f6e580.png)

**Comment by Hirogen** [comment]
What Screen-Resolution and DPI are you using? Bigger Smaller DPI then 100%, also are you using  Courier New as System-Font? I highly discourage the use of a monospaced fonts as System-Fonts, this will make for all kinds of funky looking UIs.

**Comment by Hirogen** [comment]
@keai4le is this still a problem when you dont use a monospaced system font?

**Comment by Hirogen** [comment]
Works with the standard font of windows, please reopen the issue if this is still a problem on your side
