### ISSUE TITLE
Using RegexColumnizer 

### ISSUE THREAD

**Issue by TekBear** [zarunbal/LogExpert#173]
**Testing logexpert v1.5 5493 + regexColumnizer + static local file + .Net 3.5 + Windows 6.0**
- Test data file used (< 2Kbytes)
[test2_log-20200529-022311.txt](https://github.com/zarunbal/LogExpert/files/4768733/test2_log-20200529-022311.txt)

- Screenshot showing settings and output result
![TI logexpert example](https://user-images.githubusercontent.com/5044866/84464497-3d871400-aca7-11ea-9305-8b354d695c23.jpg)

For testing  I manually added line 2. Line 2, col 10 .. end-of-line is what line 1 contained (ie. it began with the "*" character). I don't understand what is going on in first line given regex pattern why is text before the "Z" being stripped with that regex:

> `(?<Time>..:..:..)(?<Msg>.+)`

I can see times have been converted to local time. I was expecting line 1 would begin with a "*" char not "Z" in "Msg" column. Is this expected behaviour ?

**Testing logexpert v1.7.1 + regexColumnizer + same static local file (see above) + .Net 4.6 + Windows 6.0**
Same result but now "convert to local time" feature is missing and "Timeshift" option is not supported in regexcolumnizer. My goal is to convert to local time, so this is worse than older version for me. None of the other columnizer choices will handle this inconsistent format (= time column occasionally has value "*********").  Another reason to consider #172.

Can anyone test reproduce the behaviour with  test data + regexColumnizer (above) under latest version. I could not test latest logexpert 1.8.7 + .Net 4.7.2, as Windows 6.0 only supports up to .Net 4.6. Does anyone know if logexpert 1.8.7 will compile under .Net 4.6 and is that something I could do?

**Comment by TekBear** [comment]
I now get an acceptable result for that annoying "folding@home client log" in UTC time and it now displays in local time.

**Testing logexpert v1.5 5493 + regexColumnizer + static local file (see above) + .Net 4.6 + Windows 6.0**

Changed regexp to fix problem:
> `(?<Time>^........)(?<Msg>.+)`

- Screenshot
![TI logexpert example2](https://user-images.githubusercontent.com/5044866/84516755-cf6f3b00-ad00-11ea-92ae-351d18599aab.jpg)

Logexpert v.1.7.1 or higher can not do the same thing so back to consider #172 again assuming I updated to a newer version of Windows.

**Comment by Hirogen** [comment]
> I could not test latest logexpert 1.8.7 + .Net 4.7.2, as Windows 6.0 only supports up to .Net 4.6. Does anyone know if logexpert 1.8.7 will compile under .Net 4.6 and is that something I could do?

Download it and compile it with 4.6.

But why are you running it on a no longer supported Windows Version? You do realize there are no security updates for windows vista (NT6.0), so your pc is at risk. Extended Support for Windows Vista ended 2017!

**Comment by TekBear** [comment]
Yes I realise all the risks - it has minimal exposure to the Internet. I don't know how to compile .Net but will look into it. Any how to guides would be useful.

**Comment by Hirogen** [comment]
> Yes I realise all the risks - it has minimal exposure to the Internet. I don't know how to compile .Net but will look into it. Any how to guides would be useful.

1. Download the source-code
2. Load the snl file into Visual Studio / Visual Studio Code (https://code.visualstudio.com/, its free, it works)
3. Change the Target to .net 4.6 => Compile 
4. Go to the debug / release folder and start the compiled exe.

How to change the target framework => https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2019

**Comment by Hirogen** [comment]
@TekBear did you compile it with .net 4.6 and did it work, or did you upgrade to win10?

**Comment by TekBear** [comment]
Will need win 7 or above to run vs code. When I have that I  will try it.
