### ISSUE TITLE
[Request] Lizence upgrade to GPL2 and make it possible ;)

### ISSUE THREAD

**Issue by blackcrack** [zarunbal/LogExpert#174]
# Bug
not usable in Reactos because wrong Licence 

Important questions
-sourcecode

# Feature
Implementing sftpfs in reactos
https://github.com/reactos
Reactos is is a WinNT, 
All Windows XP-Software should running in Reactos
Reactos is the Same Architecture like WinNT from MS, but free and unter GPL2
Reactos is currently in Alpha, 

Please provide a rough use case so its possible to get a deeper understanding how the feature would be used.

Changing the Source Code to GPL2 , because you're 
sftpfilesystem could be really helpful in Reactos ;)
To have a Possible for adding and connecting a sftp to the drives or 
in direction of unc-path to connecting a other sftp-server directly
over path like 
[C:\path\path\______________]  

the Possible to hang it in as Drive like S:\path\path by Start of the System
or direct connect via lnk and explorer or direct typing in the adressline
and support for Total Commander and other Filemanager
like :  
[sftp:\name:password@server.dom:0000\path\path\_____]  

so as e.g. in the commandline of TC:
[cd sftp:\name:password@server.dom:0000\path\path\____]  

# General
Please don't forget, this repository is maintained in free time! The tasks will be tackled as soon as there is time.

yes, :)

before you do, should you silent ask Stas'M if this a good idea and if you can do that.
but , nothing about me. and "Mark Jansen" don't like me.. so psst,,

if you have read this issue, close it...
to hide it..
Thank you :))

best regards
Blacky

**Comment by Hirogen** [comment]
I'm not sure, but could you elaborate, why the MIT-Licence is not applicable in your case?

**Comment by blackcrack** [comment]
Well, MIT is more Close as GPL2.. and the MIT-Code can not use in a clean GPL2 Repository.. so it must be conform..
:)

**Comment by Hirogen** [comment]
> Well, MIT is more Close as GPL2.. and the MIT-Code can not use in a clean GPL2 Repository.. so it must be conform..
> :)

I still don't get it, with the MIT Licence, you can literally do what ever you want, as long as the copyright is maintained, why should you not be able to use it in a project with GPL2?

It seems more like GPL2 has a stronger restriction then MIT, but I'm no expert on Licensing.

**Comment by blackcrack** [comment]
well, you also not \*g*
this is why i have ask/call for it, because i am not a expert too.. :smily
could it possible if you implementing sftpfs in reactos, could be a big thing, because supporting a sftp-connection in a WinnT if Stas'M(BinaryMaster) it's allow.. :wink:

**Comment by Hirogen** [comment]
sadly my proficiency with sftp is not high enough to implement it in another project.
