### ISSUE TITLE
setup.exe gone?

### ISSUE THREAD

**Issue by jol64** [zarunbal/LogExpert#175]
# Bug/Feature
[LogExpert 1.8.5](https://github.com/zarunbal/LogExpert/releases/tag/v1.8.5) provided a setup.exe, which is very handy for automated installation/update on mulitple systems. Can you please provide that with all releases? At least it is missing in [LogExpert 1.8.7](https://github.com/zarunbal/LogExpert/releases/tag/v1.8.7).

Thanks, Joachim

**Comment by Hirogen** [comment]
InnoSetup was not created, I think it was removed again by @zarunbal, probably due to the release pipeline not supporting it, but I don't know.

**Comment by Hirogen** [comment]
will be added again in 1.8.8
