### ISSUE TITLE
[Feature request] Resizable "Text filter" field

### ISSUE THREAD

**Issue by Pr0metheus2** [zarunbal/LogExpert#177]
# Feature

![image](https://user-images.githubusercontent.com/9161285/86579076-1a394700-bf7d-11ea-9e0d-e014ab710aa7.png)

Can we increase width of "Text filter" field, or could that be automatically resized according to number of characters present?
I am using Regular expression and more than one command to filter out the result, but this field is quite short.
Also history of text filter is with fixed width and if there ase similar commands, they all looks same.

**Comment by Hirogen** [comment]
I still got 2 other issues open, that I'm working on very slowly, but as soon as those are finished, I will try to find a solution for this :)

**Comment by Hirogen** [comment]
#193 merged, feature has been added
