### ISSUE TITLE
Custom Columnizer

### ISSUE THREAD

**Issue by egeozcan** [zarunbal/LogExpert#18]
Hi, is there a way to create a columizer for arbitrary formats? I couldn't parse IIS logs with the default columnizers. In that case data is separated by spaces.

**Comment by zarunbal** [comment]
you have always the possibility to create a Plugin with C# which parses the log files. I'll try to create this weekend a Wiki entry which covers the creation of a Plugin.

You could try to use the CSV Columnizer if you change the seperator to tab/space?

**Comment by zarunbal** [comment]
I have started to write a wiki entries for the [Plugins](https://github.com/zarunbal/LogExpert/wiki/Plugins). There are some Informations but that have to be extendended and maybe I have to change the Layout. I'm currently not satisfied with the entries.

**Comment by egeozcan** [comment]
Hi, thank you very much. I tried to use the CSV Columnizer with a space but the application crashed. I'll investigate further and provide you with the details when I have more time. 

Is there some auto-loading of dlls for columnizers? That'd be great as I can just develop something for IIS as a plugin, without making a pull request to bloat this codebase.

**Comment by zarunbal** [comment]
Every dll placed in the `plugins` folder is loaded into LogExpert

**Comment by zarunbal** [comment]
Added this information to the [Plugins](https://github.com/zarunbal/LogExpert/wiki/Plugins) Wiki entry.

**Comment by natenho** [comment]
Hello @egeozcan , could you please share your plugin (maybe a project in your repository)?

**Comment by egeozcan** [comment]
Hi @natenho, sorry, I tried using the CSV Columnizer again and it worked. Less code I have to write the better^^
