### ISSUE TITLE
SFTP plugin does not persist keyfile settings

### ISSUE THREAD

**Issue by daniel-brosche** [zarunbal/LogExpert#181]
LogExpert Version: 1.8.7
Windows Version: Windows 10 Enterprise
Lokal file or Network: Network SFTP
Is this version specific or a new problem: seems specific when SFTP Plugin used

After application restart the settings of the sftp plugin are always lost (keyfile path, keyfile type).
It seems that this settings also can't be exported/imported. Tried this as workaround...

I have the portable mode activated and also specified the app folder as persistence file location.

**Comment by Hirogen** [comment]
Does this also happen if you deactivate portable mode? 

Just to be sure, if its portable mode or not!

**Comment by daniel-brosche** [comment]
Yes, I have checked that. It also happens without portable mode.

**Comment by daniel-brosche** [comment]
Can I hel further to solve this issue? It is really annoying...

**Comment by Hirogen** [comment]
> Can I help further to solve this issue? It is really annoying...

No not really, currently a lot to do at work and in private, so I have a little less time to code at home :(

**Comment by Hirogen** [comment]
PortableMode now saves all plugin configuration in its own "portable" folder in the application startup folder, please test this with the release 1.8.8 again. (https://github.com/zarunbal/LogExpert/pull/234 and https://github.com/zarunbal/LogExpert/pull/235)
