### ISSUE TITLE
WPF?

### ISSUE THREAD

**Issue by mohamead** [zarunbal/LogExpert#183]
Is there any plans to upgrade from WinForms to WPF?

**Comment by Hirogen** [comment]
> Is there any plans to upgrade from WinForms to WPF?

Not in the near future

**Comment by Hirogen** [comment]
Just a Sidenote, it would probably be best if we go the .net Core 3.1 route and try to make the UI platform independent as much as possible.

Since .net Framework will no longer be supported by MS in the near future and everything will transfer to .net 5
