### ISSUE TITLE
Multi-file doesn't guarantee file ordering

### ISSUE THREAD

**Issue by natenho** [zarunbal/LogExpert#191]
# Bug

Important questions
- LogExpert 1.70 (also reproducible in last version)
- Windows Server 2012 R2 (also reproducible in Windows 10)
- Local
- Used Columnizer: No

According to https://stackoverflow.com/questions/38319915/c-sharp-openfiledialog-to-select-multiple-files-with-same-order-as-user-selects/38319967#comment117205495_38319967, the order of the selected files are not guaranteed in multi-file.

Such behavior causes log files to be shown in undesirable order.

![image](https://user-images.githubusercontent.com/4236481/109083171-288ecb80-76e4-11eb-8286-0a77a4054d68.png)

**Comment by Hirogen** [comment]
#192 merged and added this feature
