### ISSUE TITLE
SFTP plugin : strange place for dll

### ISSUE THREAD

**Issue by pedefe** [zarunbal/LogExpert#200]
Hello,

On Window 10/64, to Raspberry Pi, I wanted to use sftp plugin.
- If I put SftpFileSystem.dll & ChilkatDotNet47.dll in ./plugins forder, doesn't works.
- If I put SftpFileSystem.dll & ChilkatDotNet47.dll in ./ forder, doesn't works.
- If I put SftpFileSystem.dll & ChilkatDotNet47.dll in both ./plugins & ./ forder, it works.
Why ?
Best regards.

**Comment by Hirogen** [comment]
Could you elaborate, what you did exactly and how you did it?

**Comment by Hirogen** [comment]
those dlls are in the pluginsx86 folder!

**Comment by Hirogen** [comment]
Same vicinity like https://github.com/zarunbal/LogExpert/issues/243

**Comment by Hirogen** [comment]
https://github.com/zarunbal/LogExpert/issues/273
both have the same plugin

**Comment by Hirogen** [comment]
this is fixed with https://github.com/zarunbal/LogExpert/pull/280
