### ISSUE TITLE
Reforking and Working on a new Fork

### ISSUE THREAD

**Issue by Hirogen** [zarunbal/LogExpert#205]
Hi Contributors,
@igitur , @detlefs @aliask @zarunbal @jonathanwatters @fremag @BestFriend83

open pull requests by:
@hakanostrom, @natenho, @budul, @jsuppe, @burki169

since @zarunbal is no where to be seen since 2020 and there are 7 Pull Requests, that fix bugs and should be merged, I plan to use the fork I created => https://github.com/Hirogen/LogExpert, If any of you are interested to be a second or third maintainer pls contact me

Contributors with open pull request, pls recreate them into my fork, I will check them and Merge them, after that I will create a new release.

If @zarunbal is reachable again, everything can be remerged to this repository!

**Comment by igitur** [comment]
Instead of creating a fork, I'd urge you to try exhaustively to contact @zarunbal and try to convince him to make you a project administrator.

**Comment by natenho** [comment]
@igitur Why not the fork? I mean..it seems to be a good way to resume the development and switch back later. What kind of problem do you see?

**Comment by zarunbal** [comment]
@Hirogen can you give me two weeks? Then I have my move finished and should be settled at my new location. Then I can see how I can add people which are willing to further develope as admins or whatever this is here called. 

Who would be interested to be added as maintainer here?

**Comment by zarunbal** [comment]
> I would be intereseted

I added you as a contributor. You should have now access. For a new release I have to update the tokens in the pipeline again to work fully (nuget publish and so on)

> Always :D I use it on a daily basis for work!

Great to hear, that was my motivation too

**Comment by Hirogen** [comment]
> I added you as a contributor.
thanks :)

**Comment by Hirogen** [comment]
@zarunbal I created a pre-release, since I couldn't get appveyor and the local build to create a 1.8.8 version :see_no_evil:

**Comment by Hirogen** [comment]
@ the contributors, are you interested in a discord server, where we can exchange faster?

**Comment by zarunbal** [comment]
> @zarunbal I created a pre-release, since I couldn't get appveyor and the local build to create a 1.8.8 version 🙈

I'll try to get it running again the next days

**Comment by spacemanspiff2007** [comment]
> I created a pre-release

Will the 1.8.8 be available through choco?

**Comment by Hirogen** [comment]
> Will the 1.8.8 be available through choco?

This has to be done by @zarunbal, I currently don't know how that works :)

**Comment by Hirogen** [comment]
> > I created a pre-release
> 
> Will the 1.8.8 be available through choco?

if 1.8.8 is no available via choco please open a new issue.

Since I can maintain the project, this issue is closed
