### ISSUE TITLE
Use consistent encoding names in settings and menu

### ISSUE THREAD

**Issue by Akaizoku** [zarunbal/LogExpert#208]
# Issue

The name of the character encodings available in settings does not match the name of the encoding available from the menu (View/Navigate > Encoding).

| Encoding     | Settings     | Menu         |
| ------------ | ------------ | ------------ |
| ASCII        | us-ascii     | ASCII        |
| Windows-1252 | Windows-1252 | Windows-1252 |
| ISO-8859-1   | iso-8859-1   | ISO-8859-1   |
| UTF-8        | utf-8        | UTF8         |
| UTF-16       | utf-16       | Unicode      |

![Settings options](https://user-images.githubusercontent.com/8892526/151178101-1d5ab6bd-7ffb-417f-b49b-efb83a9dcb9a.png)
![Menu options](https://user-images.githubusercontent.com/8892526/151178114-90e75d4b-3b75-4fc1-96b1-b769198b9a05.png)

**Comment by Hirogen** [comment]
Should be fixed with #227
