### ISSUE TITLE
Crash when dragging other stuff over logwindow

### ISSUE THREAD

**Issue by jonathanwatters** [zarunbal/LogExpert#21]
Suggest checking for null after 
object data = e.Data.GetData("Shell IDList Array");
in  LogWindow_DragOver(object sender, DragEventArgs e)  (LogTabWindow.cs)

e.g.: 
add
if (data == null) return; // prevent other dragged items crashing

Should I attempt to commit this to Development branch and raise pull request?

**Comment by zarunbal** [comment]
Sure fell free to create a Pull Request for the Developtment branch. Improvements are always welcome!

**Comment by jonathanwatters** [comment]
I've committed the change to my local Development Branch, but pushing it
results in


git -c diff.mnemonicprefix=false -c core.quotepath=false push -v origin
Development:Development

remote: Permission to zarunbal/LogExpert.git denied to jonathanwatters.



fatal: unable to access 'https://github.com/zarunbal/LogExpert.git/': The
requested URL returned error: 403



Pushing to https://github.com/zarunbal/LogExpert.git



Completed with errors, see above.



I was expecting to push to Development and raise a Pull Request from there
to master?


Or do I need to create a branch off Development to commit and push my
change to, then create a pull request to merge THAT into development?


It's my first time on a github project.....



regards,


Jonathan

**Comment by zarunbal** [comment]
As far as I see (I don't have that much experience too) you have to fork this repo and then make the changes and then you can create a Pull Request. https://guides.github.com/activities/forking/#making-a-pull-request

If this is to much work I integrate your changes. Just attach your changes and I'll add them to the branch.

**Comment by jonathanwatters** [comment]
I think I've sussed it - pull request now awaiting approval and merge.
Yay.

**Comment by zarunbal** [comment]
Thanks for your contribution, I really appreciate this! I'll close this bug.

**Comment by zarunbal** [comment]
The new release with your contribution is out. Feel free to test it and give feedback.
