### ISSUE TITLE
Feature Request: Allow LogExpert to be opened via command line with target session file as a parameter.

### ISSUE THREAD

**Issue by jrobi-atx** [zarunbal/LogExpert#229]
#33 
Allow for reopening target files and setting up required filter windows at time of startup of LogExpert.  

Currently when using multiple files with multiple instances the session capabability is hit-or-miss....I have already opened another issue for this.  When this gets nailed down, it would be great to be able to open LogExpert with a target session file as a parameter so that all of the files and additional filter windows (including the filter window type [console or floating] and filter window locations (if floating) could be brought up without having to manually reopen everything and reposition everything.  And hopefully this functionality would be independent of any other LogExpert that is already running or was running last.  

This way you could get right to work.

**Comment by Hirogen** [comment]
this should be fixed with #235 
in portable mode every instance now saves there session files in the sessionfiles-folder in the application startup folder
