### ISSUE TITLE
.lxp file write permission error occurred during network files

### ISSUE THREAD

**Issue by ahmetuk** [zarunbal/LogExpert#24]
![image](https://user-images.githubusercontent.com/8466877/35971557-8273baa6-0cdf-11e8-8b81-0cf4aadf611e.png)

Got error file write permission error occurred during network files while on save session or exitted the program. But lxp file is saved. I configured my .lxp file is near the "log" directory where is under <USER_DIR>\AppData\Roaming\LogExpert

Regards...

**Comment by zarunbal** [comment]
@ahmetuk  Please answer following questions and attach the generated log file ([Wiki](https://github.com/zarunbal/LogExpert/wiki/FAQ#logging))
- Version?
- You have set the "Persistence file location" to "Same directory as log file" did I understand that right?
- Do you have Roaming Profile?
- What permissions you have on the file if this was generated?
- Is this a full crash or a message box during execution?

**Comment by ahmetuk** [comment]
Hi, according to your questions;
- 1.6.7 Zip edition
- Yes
- No. Under standart windows user directory.
- Windows 10 Ent. Full Control Permissions
- Just a message box.

**Comment by zarunbal** [comment]
@ahmetuk could you please attach the generated log file?

**Comment by ahmetuk** [comment]
Hello, sorry for late return. No need to attach log file. 

We were trying to shared session data file. I tried many times but i couldn't success about passing domain username and password. 

Finally, i and the others put the lxp file to our local computers. The problem was solved. Thank you.

**Comment by zarunbal** [comment]
Thanks for your response. If there is any problem feel free to create a new issue
