### ISSUE TITLE
Could not load file or assembly Newtonsoft.Json, Version=13.0.0.0

### ISSUE THREAD

**Issue by KoalaBear84** [zarunbal/LogExpert#241]
# Bug

Looks like this only happens when you have a previous version (1.8.5 in my case), because when I test it in Windows Sandbox it is working.

My previous version was installed to "C:\Programs\LogExpert.1.8.5", new version to "C:\Program Files (x86)\LogExpert", maybe that is also a factor.

```
---------------------------
LogExpert
---------------------------
Cannot open connection to first instance (Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.)
---------------------------
OK   
---------------------------
```

The zip version is working, but the installer [LogExpert.Installer.1.9.0.exe](https://github.com/zarunbal/LogExpert/releases/download/v1.9.0/LogExpert.Installer.1.9.0.exe) is not installing the "Newtonsoft.Json.dll" in the 'root' directory, but in the plugins directory, probably because it is a new dependency and forgot to exclude it :) Although I can only see this exclusion/filter: https://github.com/zarunbal/LogExpert/blob/master/build/Build.cs#L95

If I move "Newtonsoft.Json.dll" it from plugins to the root, it is working.

**Comment by Hirogen** [comment]
Updated the setup and the [LogExpert.Installer.1.9.0.exe](https://github.com/zarunbal/LogExpert/releases/download/v1.9.0/LogExpert.Installer.1.9.0.exe)with the correct path, this should now work

**Comment by KoalaBear84** [comment]
Checked, it's working 👍
