### ISSUE TITLE
Blank line after each file change

### ISSUE THREAD

**Issue by HelloZeroNet** [zarunbal/LogExpert#25]
By watching the out.log file generated by this simple python script results in empty line after each update
```
import time

out = open("out.log", "w")

while 1:
	out.write("%s\n" % time.time())
	out.flush()
	time.sleep(1)
```

Switching to "Use legacy file reader (slower)" fixes this problem.

![image](https://user-images.githubusercontent.com/10350359/35978116-205128d0-0ce5-11e8-9668-a7f91a0cd4c0.png)

**Comment by zarunbal** [comment]
Thanks for this script to reproduce the error. I can reproduce it and will have a look into it to fix this.

**Comment by zarunbal** [comment]
ups, missed to write here with the previous release. I'm sorry! This issue was resolved previous release and I'll close this issue. If there are any problems feel free to reopen this issue or create a new one.
