### ISSUE TITLE
Text filter dropdown arrow inaccessible

### ISSUE THREAD

**Issue by mrowrpurr** [zarunbal/LogExpert#254]
After upgrading to 1.9.0 (_using the latest version that introduced Dark Mode_), I can no longer see the down arrow in the Text filter dropdown:
![Screenshot (184)](https://user-images.githubusercontent.com/87039589/181934829-6202de69-5b65-4d86-be96-15a34b88c4ea.png)

Even if I resize the Text filter all the way that it'll go to the right on my 1080p monitor, I still cannot see the down arrow:
![Screenshot (185)](https://user-images.githubusercontent.com/87039589/181934890-61a5656e-04a0-4cb0-9e20-d5baef14220e.png)

The right area (with `Search` `☐ Case Sensitive` `☐ Regex` etc) seems to cover up the down arrow (?)

**Comment by jrouzies-fr** [comment]
What do you mean by wrong numbers?

I'm checking but I am a bit clueless of what happened to that box, even without the theme:

![image](https://user-images.githubusercontent.com/57990274/182178678-d6f1cd7c-2217-4e5c-8065-a145394d1cd9.png)

I can **extended** it left right but no dropdown (that extension was not possible in previous release). It's a bit like the type changed!

From the PR only the size changed a bit:

![image](https://user-images.githubusercontent.com/57990274/182180055-23bcbe10-b651-4154-a046-abb780ac4d82.png)

![image](https://user-images.githubusercontent.com/57990274/182180183-84d705cf-e767-4901-ab4e-2d8911a38448.png)

The type is still good

![image](https://user-images.githubusercontent.com/57990274/182180504-9b4369f8-27a0-443b-90c7-bb90ca381984.png)

In the designer it looks fine:

![image](https://user-images.githubusercontent.com/57990274/182182519-e9ac15b6-027c-472f-b0e7-e39102bb4ef1.png)

**Comment by Hirogen** [comment]
will close this issue after building a new version on the weekend

**Comment by Hirogen** [comment]
Just created a Testrelease 9001 for the dark-theme => https://github.com/zarunbal/LogExpert/releases/tag/v.1.9.1.9001_DarkTheme

this problem should now be fixed
