### ISSUE TITLE
Missing package 1.9.0 on chocolatey.org

### ISSUE THREAD

**Issue by Matze693** [zarunbal/LogExpert#256]
# Bug
Version 1.9.0 is not available on [chocolatey](https://community.chocolatey.org/packages/logexpert).

**Comment by Hirogen** [comment]
I contacted the admins on chocolatey website, now need to wait till they make me a maintainer with the package and after that will update :)

**Comment by Hirogen** [comment]
I have become a maintainer for the project, i also updated the package, just need to wait till its updated :)

**Comment by Hirogen** [comment]
Package has been updated: https://community.chocolatey.org/packages/logexpert/1.9.0
