### ISSUE TITLE
How to keep settings and highlight rules when updating from 1.8.5 to 1.9.0?

### ISSUE THREAD

**Issue by greenseeker** [zarunbal/LogExpert#261]
After updating to 1.9.0, my highlighting rules are gone. I was able to go back to 1.8.5 and they are present again.
I exported settings from 1.8.5, re-upgraded, and then imported the .dat file but it has no effect. 1.8.5 doesn't seem to have any way to export json.

How can I migrate my settings and rules to the new version?

**Comment by Hirogen** [comment]
Install this 1.8.7 Version: https://github.com/zarunbal/LogExpert/releases/tag/v1.8.7-json-options, then save the options once, and you should see a settings.json in the same folder as your settings.dat.

With 1.9.0 the settings are saved as a json!

**Comment by Hirogen** [comment]
Did the 1.8.7 help?

**Comment by greenseeker** [comment]
Yes I was able to get the settings carried over. Thanks.
