### ISSUE TITLE
FR: Highlighting and Trigger settings should have "match entire word" and "case sensitive" options

### ISSUE THREAD

**Issue by nitin065** [zarunbal/LogExpert#266]
It would be helpful when we want to see lines where the "ERROR" type of logs are logged but not wherever the "error" string appears.

Current LogExpert version: 1.9.0

**Comment by Hirogen** [comment]
Highlighting already supports this

![image](https://user-images.githubusercontent.com/8225398/190966149-ca59d8de-c622-4365-88cb-0cc2dff81a00.png)
