### ISSUE TITLE
ChilkatLog, trial has expired?

### ISSUE THREAD

**Issue by QueRoxa** [zarunbal/LogExpert#273]
# Bug
Tried to access our server, and get an error from Chilkat saying the trial has expired.  File isn't opened.

Important questions
- LogExpert v1.9.0
- Network file

![image](https://user-images.githubusercontent.com/16065051/200028118-e6e2c44e-e5ee-4802-9067-e07cfb844105.png)

**Comment by Hirogen** [comment]
interesting this seems to be some third party dll that has been licensed

**Comment by Hirogen** [comment]
this is the sftp implementation, not sure if this is still needed.

If sftp is used, it needs a new implementation with a library that is maintained and does not cost any money, best open source, i found ssh.net but that I need to familiarize myself with it, before I can implement the alternative to chiklat stuff
