### ISSUE TITLE
copy to clipboard: always add line number

### ISSUE THREAD

**Issue by jan831** [zarunbal/LogExpert#275]
# Feature
when copying a line from the "filtered lines", the line number is prefixed.

when copying from the main view, the line numbers are not added.   It would be nice if we can have the same format for pasted lines from both views.   

It also makes it easier to create a separate file with selected log lines.    I always copy the "needed" lines to a separate file (with different filters) and sort them by line number.

**Comment by Hirogen** [comment]
will be added with the #277 in the next release
