### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by HelloZeroNet** [zarunbal/LogExpert#28]
It would be nice if I could bring LogExpert with myself on an usb stick with the same settings. 

Like if there is a `settings.dat` next to `LogExpert.exe` then use that otherwise use the appdata directory.

Btw: Thanks for this application it made my life much easier

**Comment by zarunbal** [comment]
what settings you want to be portable?
- columnizer "selection"
- highlighting
- performance settings
- ...?

**Comment by HelloZeroNet** [comment]
The ideal would be not save anything in appdata, but store all the settings in the same directory as LogExpert.exe

**Comment by zarunbal** [comment]
I assume that then anything that is saved under the current user profile should be placed in the same folder? Because there are more files which are generated
- Persistence files (Can be configured to be like next to the log file, but default is 'My Documents')
- Logs

**Comment by Dimentium** [comment]
Your app is great! 
It's only one boring thing - sync app settings between some PC after changing Highlighter rules.
Is it possible:
If a `settings.dat` **exists** next to `LogExpert.exe` (in the same directory) then use it instead appdata. Otherwise keep current behaviour.
Thank you very much!

**Comment by spacemanspiff2007** [comment]
Can't we even make it easier?
If a folder "settings" next to ``logexpert.exe`` exists use this folder otherwise use appdata?
This way there is no new settings format needed.

**Comment by Hirogen** [comment]
> Your app is great!
> It's only one boring thing - sync app settings between some PC after changing Highlighter rules.
> Is it possible:
> If a `settings.dat` **exists** next to `LogExpert.exe` (in the same directory) then use it instead appdata. Otherwise keep current behaviour.
> Thank you very much!

yes, just copy paste the file and load it from within the options or export it where ever you want

![image](https://user-images.githubusercontent.com/8225398/79966699-19b90600-848e-11ea-9d36-f1f45607ee13.png)

![image](https://user-images.githubusercontent.com/8225398/79966731-26d5f500-848e-11ea-8522-ba3b60a933f9.png)

**Comment by Hirogen** [comment]
> Can't we even make it easier?
> If a folder "settings" next to `logexpert.exe` exists use this folder otherwise use appdata?
> This way there is no new settings format needed.

not needed, see my post :)
you can import / export it from where ever you want

**Comment by spacemanspiff2007** [comment]
> not needed, see my post :)
you can import / export it from where ever you want

I know it's possible, but it's not elegant. Using the folder would require no action at all.

With import export I have to remember to do the export on the source machine and do the restore on the target machine. Every time something changes (e.g. settings, recent files, etc.)

**Comment by Hirogen** [comment]
> > not needed, see my post :)
> > you can import / export it from where ever you want
> 
> I know it's possible, but it's not elegant. Using the folder would require no action at all.
> 
> With import export I have to remember to do the export on the source machine and do the restore on the target machine. Every time something changes (e.g. settings, recent files, etc.)

why every time? only if you change the settings, to something new, logexpert does not overwrite the settings if you install or update

**Comment by spacemanspiff2007** [comment]
The goal is to achieve portable behavior. This means recent files, etc..
I observe some logs on one machine, maybe open some additional logs.
Then I go to the next machine and want to restore the same view there.
Currently this is only possible if I export/import after each settings which is not feasible.

Changing the settings folder from ``appdata`` should be a very small programmatic change which would allow exactly that.

**Comment by Hirogen** [comment]
> The goal is to achieve portable behavior. This means recent files, etc..
> I observe some logs on one machine, maybe open some additional logs.
> Then I go to the next machine and want to restore the same view there.
> Currently this is only possible if I export/import after each settings which is not feasible.
> 
> Changing the settings folder from `appdata` should be a very small programmatic change which would allow exactly that.

I don't think this is the right way.

Better would be, to just make it configurable. The Default should always be APPDATA.

> The file-system directory that serves as a common repository for application-specific data. A typical path is C:\Documents and Settings\username\Application Data or C:\Users\username\AppData\Roaming.
https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables

**Comment by spacemanspiff2007** [comment]
As I wrote:
The ``settings`` folder shall only be used when it was manually created by the user.
The default should remain ``appdata``. That's basically "configurable".

**Comment by Hirogen** [comment]
> As I wrote:
> The `settings` folder shall only be used when it was manually created by the user.
> The default should remain `appdata`. That's basically "configurable".

From a user point of view, this is unfeasible.
How should the user know, that he needs to create a "settings" folder, without writing pages long manuals?

An option for the default folder to load and save settings from would take care of the problem, and is understandable without any further information.

**Comment by spacemanspiff2007** [comment]
> How should the user know, that he needs to create a "settings" folder, without writing pages long manuals?

How about showing this in the "About" dialog or during installation:
To enable portable mode create a ``settings`` folder next to the ``logexpert.exe``.
If the folder exists all settings will be stored there.

> An option for the default folder to load and save settings from would take care of the problem, and is understandable without any further information.

How would you transfer the option to another machine without prompting the user again?

**Comment by Hirogen** [comment]
> How about showing this in the "About" dialog or during installation:
> To enable portable mode create a `settings` folder next to the `logexpert.exe`.
> If the folder exists all settings will be stored there.

That is a suboptimal UX and UI design, no information about that later on, best to just have an option in the Settings Dialog, where you can define the folder, where it's saved and loaded from

> How would you transfer the option to another machine without prompting the user again?

This option itself could be saved in the installation folder beside the executable, so no action needs to be taken, as long as the folder is copied.


Again the best option would be to have a "Settings save and load" folder option, where you can select the folder, the settings file should be loaded and saved, this is easy to understand if you see the first time and does not need to be written down anywhere in a helpfile or wikipage. 
And this option can be saved side by side with the executable, even in the app.settings itself if needed be.

Creating Folders to "add" a feature, is not very intuitive and does not translate well for the normal user that does not know the feature exist.

**Comment by spacemanspiff2007** [comment]
A proper settings implementation as suggested is even better. 👍

**Comment by Dimentium** [comment]
> > Is it possible:
> > If a `settings.dat` **exists** next to `LogExpert.exe` (in the same directory) then use it instead appdata. Otherwise keep current behaviour.
> 
> yes, just copy paste the file and load it from within the options or export it where ever you want
Yep.
But I works on 3-4 PC simultaneously  and it's really annoying to keep settings synced each time when I change rules for Highlighting or Columnizer.

Redirecting settings folder would be great - I would simply keep LogExpert folder in OneBox or network share.

**Comment by Hirogen** [comment]
> > > Is it possible:
> > > If a `settings.dat` **exists** next to `LogExpert.exe` (in the same directory) then use it instead appdata. Otherwise keep current behaviour.
> > 
> > 
> > yes, just copy paste the file and load it from within the options or export it where ever you want
> 
> Yep.
> But I working on 3-4 PC simultaneously and it's really annoying to keep settings synced each time when I change rules for Highlighting or Columnizer.
> 
> Redirecting settings folder would be great - I would simply keep LogExpert folder in OneBox or network share.

Currently working on this, should be ready in the next few days.

Here is a Quick Screenshot:

![image](https://user-images.githubusercontent.com/8225398/80025548-20bd3400-84e1-11ea-8b4a-d33c60c7ea37.png)

You can activate the portable-mode, this will create a empty file "portableMode.dat" in the directory, where logexpert has been started from (Application.StartupPath).

When Logexpert starts, it will check for the file, if its there, logexperts "assumes" he is in portable mode and will load the settings.dat from the Application.StartupPath, if not, it will read the standard path.

![image](https://user-images.githubusercontent.com/8225398/80026120-e3a57180-84e1-11ea-85e0-c8babcc6169e.png)


Currently trying to workout a few problems, just to make sure, it does not block itself in this mode.
Also I'm currently not really satisfied they way this is "configured", the portableMode Path has to be added to 2 files, and that is unnecessary code duplication.

I hope I can work this out in the next few days, then I will create a pull request :)

**Comment by Hirogen** [comment]
Finished development, created pull request.

Waiting for confirmation :)

**Comment by zarunbal** [comment]
Thanks @Hirogen for the pull request :)

See new release, feedback of the new functionality is appreciated

**Comment by Hirogen** [comment]
this has been implemented:

Portable Mode from Version 1.8.8 onward:
- configuration is saved in a subfolder "portable" in the application startup folder
  - this includes plugin / columnizer configurations 
- persistence files (sessions) are saved in a subfolder "sessionfiles" in the application startup folder
