### ISSUE TITLE
I cant open xml file - it shows blank widnow

### ISSUE THREAD

**Issue by ndinev** [zarunbal/LogExpert#281]
# Bug
I can't see content of an xml file. 
If I rename it to .log it works fine

Important questions
- LogExpert Version: 1.9.0
- Windows Version: 10
- Local file
- Used Columnizer: By default none - but I tried others - same result - no content
- Is this version specific or a new problem - tried with 1.7 - same result
![image](https://user-images.githubusercontent.com/1850067/230085080-8011c57f-0a88-4f43-923b-9b2e553dc383.png)

Optional questions(depends on the problem):
- Continuous appending log file? - no
- Size of the file - can be very small - 1KB
- some specific settings - default settings

Use case:
I just like by default all files to be treated as text files.

**Comment by keai4le** [comment]
Seems you use a columnizer
![image](https://user-images.githubusercontent.com/8185606/231039051-93707972-9445-4cd5-81a1-1ff840c7c9fa.png)

**Comment by greenseeker** [comment]
> Seems you use a columnizer ![image](https://user-images.githubusercontent.com/8185606/231039051-93707972-9445-4cd5-81a1-1ff840c7c9fa.png)

It's built-in and used automatically. You can go to **Options** > **Columnizer** and change it back to Default -- I had to check **Apply to all open files** for it to work -- but it does the same thing with the next XML file.

**Comment by Hirogen** [comment]
Under Settings => Columnizers, you can specify columnizers for specific extensions, this should help with choosing the right one for xml (default columnizer probably best)

**Comment by ndinev** [comment]
Thanks all. I am closing this question
