### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by hraab** [zarunbal/LogExpert#3]
Would be nice if you also mention the original author (which is me) in the license file, even tough I'm not active anymore in this project.

Btw: MIT license requires to keep the copyright notice. So your "edit" is a violation. :)

**Comment by zarunbal** [comment]
Sorry, my bad for the wrong License Statement, thanks for your hint. Was to quick with adding just the autogen MIT license. I did not want to remove your notice of author.  :)

I changed the file if you please give a short notice that this is now ok for you

**Comment by hraab** [comment]
No worries. Thanks for changing. 
Btw: I also migrated to GitHub - I didn't notice that you already did. :) But since you're actively contributing I linked to your repo on the good by message on codeplex. :)

**Comment by zarunbal** [comment]
Thank you for the link on codeplex to this repository
