### ISSUE TITLE
Offer option save Persistence+Logfile in installation (sub)directory

### ISSUE THREAD

**Issue by pstein** [zarunbal/LogExpert#34]
I miss an option to save logfile and persistence file in a sub directory "log" of current installation directory.

When I put LogExpert onto an USB flash drive and drive letter changes the sub directory should change automatically as well.

So I need a relative folder definition ".\log" (mind the dot)

Can this be added in the next release?

Thx

**Comment by zarunbal** [comment]
I don't understand what you mean with save logfile and persistence in a specific folder (e.g. subfolder from current installation)? Could you provide a rough use case so I get a idea how this would be used.

Should LogExpert copy the logfile to the subfolder and then read it in?

Your described behavior would as far as I understand match the option under "settings -> persistence -> "Same directory as log file""?

This feature is related to #28 with my current understanding.

**Comment by zarunbal** [comment]
No feedback, closing this Feature Request. If  you have some feedback feel free to reopen this
