### ISSUE TITLE
Feature Request: Reduce space gap between lines/line height

### ISSUE THREAD

**Issue by pstein** [zarunbal/LogExpert#36]
The line height is very high. I want to see as many lines in the window as possible without scrolling.

So can the space gap between lines somehow be reduce e.g. (to one pixel) in the next release?

Thx

**Comment by Hirogen** [comment]
line height is based on Font Size, you can make a selected line bigger, by pressing Enter or smaller by pressing backspace, if you need to see more lines, you can change the font size
