### ISSUE TITLE
Bug - Hex char 0 (null)

### ISSUE THREAD

**Issue by Pr0metheus2** [zarunbal/LogExpert#38]
# Bug
Hello, I've found a bug, will try to describe it:

Bug No.1:

1. Open attached .log file in LogExpert
2. Double-click on serial number (digits inside " ")on line no.3 - space char and quotation mark will disappear
3. Double-click on serial number on line no.4 - serial number with quotation mark will disappear

Bug No.2:

1. Open attached .log file in LogExpert
2. Press <Ctrl+A>, then <Ctrl+C> for copying into clipboard
3. Open Notepad, or Notepad++ or whatever editor you have
4. Press <Ctrl+V> for paste - you will see only two lines are copied from clipboard with missing quotation mark at the end of line 2, also rest of the copied file is missing.

Important note:
It seems that hex NUL (null) char is causing this issue. So, on line 2, there is no space char after serial number, but NUL char instead and vice versa.
[testfile.log](https://github.com/zarunbal/LogExpert/files/1788932/testfile.log)

![image](https://user-images.githubusercontent.com/9161285/37089921-b03a9a6c-2202-11e8-9131-140fd672b761.png)

- LogExpert Version 1.6.7
- Windows Version 7 x64
- Local file

**Comment by zarunbal** [comment]
Hmm, I'm wondering how to display NUL in the UI. Currently I have two solutions:
- Replace it with the UTF8 Symbol U+2400 (␀) (from [wikipedia](https://en.wikipedia.org/wiki/Null_character))
- Just filter it out (This is not my favorite, because of the dropped information)

The Data which is copied into the clipboard will be untouched (Except the current two bugs)

What would you @Pr0metheus2 recommend?

**Comment by Pr0metheus2** [comment]
And what about replace with space char, hex 20 ?

**Comment by zarunbal** [comment]
With Windows Localization in my understanding is no difference, the display is handled by the font.

Maybe I add a setting in a config file to change this behavior / replacement.

**Comment by Pr0metheus2** [comment]
Its up to you, both solutions are OK. Settings for selection would be probably the best solution.
Thx.

**Comment by zarunbal** [comment]
@Pr0metheus2 currently I have not that much time. Maybe I can drop a Beta for your problem

**Comment by Pr0metheus2** [comment]
Thanks @zarunbal , it's ok, I will wait for proper update, it's not necessary to make beta version.
Hopefully you will have more time for doing this job!

**Comment by zarunbal** [comment]
Some changes later. The implementation is that everything below Win8 the Null char is replaced with a space and everything above uses the UTF8 Symbol.

Interesting finding with the Null char, N++ replaces the Null char on copy to clipboard with a space. I found that if the program tries to add a string to the clipboard with a Null char the string is truncated at the Null char.

**Comment by zarunbal** [comment]
Release 1.6.13 is out there with the fix. I close this issue. If there is still a problem feel free to reopen this issue.

**Comment by sameasiteverwas** [comment]
>>everything below Win8 the Null char is replaced with a space and everything above uses the UTF8 Symbol


Windows 10, LE 1.6.13
**Many people I know use LE to read log files that are delimited with SOH (or sometimes other chars).**
1=ABC53=623x-555=xyz-123-a-abc8300=2  etc
1=DEF53=asdf123-6-3355=wtt-123-a.bd98798=123  etc
The SOH now appears as a BOX.
![image](https://user-images.githubusercontent.com/22668091/46684970-f84d3d80-cbb9-11e8-8f9f-66a5cf0a090a.png)

This makes readability very challenging with very large, busy files.

With previous versions, it was nice to have SOH displayed as space.
To emulate this, I now apply a final hightlight rule:
search string:  [\x00-\x1F]+
Case sensitive, RegEx
Foreground color = custom (white), background color n/a
Word Mode
No Background
This turns every SOH white.
This works fine with a white background.
![image](https://user-images.githubusercontent.com/22668091/46685037-1f0b7400-cbba-11e8-9af6-3d3171eab883.png)

A problem occurs when I have previous rules highlighting lines to a color other than white, the SOH BOX shows up as white on a colored background.
![image](https://user-images.githubusercontent.com/22668091/46684900-c2a85480-cbb9-11e8-9658-7aea6ff6eee7.png)


A few ideas to resolve this issues:
#1 Configurable control character displays.
#2 Highlighting and action trigger, Coloring, Foreground color= none? transparent? no foreground?

**Comment by zarunbal** [comment]
@sameasiteverwas thanks for pointing out this problem. Could you please create a new issue for this. I know this is somehow related but on the other hand its a independent bug ;)
