### ISSUE TITLE
Trojan detected by Windows Defender in latest release

### ISSUE THREAD

**Issue by Olethros** [zarunbal/LogExpert#46]
# Bug
Release Version 1.6.10 is continually detected as a trojan by Windows Defender
I hope this is a false positive, however more action is required by the developer to ensure this.

**Details**
- LogExpert Version 1.6.10
- Windows Version Windows 10 v1709 (Build 16299.309)
- Local file
- Could not launch, logexpert exe was quarantined - threat detected as Trojan:Win32/Critet.BS

I have already submitted a sample to Microsoft as a corporate user - recieved answer that file is safe, however new definitions still flag it as unsafe.
Have also submitted both EXE and entire zip to virustotal for scanning. EXE scans clean

**Action required**
As the developer, please submit EXE for analysis at https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by zarunbal** [comment]
Thanks for your info. I'll check by microsoft which steps should be taken that this report doesn't happen. Interesting is that VirusTotal the Microsoft Engine nothing reports. 

Are you using Windows Defender for Normal users or the corporate version?

**VirusTotal** 
- [LogExpert.exe](https://www.virustotal.com/de/file/c31b4ed3ff1250f4c05dc7172996f653d92e9442e2dd8fde4fcba596e53cbbaa/analysis/) 0 / 64  
- [LogExpert-1.6.10.zip](https://www.virustotal.com/de/file/ece7aa778d27e82dd116badc28e16c41ec142803b75083e57e7e00936ca771c6/analysis/)  0 / 58

**Comment by zarunbal** [comment]
I don't have any of the microsoft solution currently working so I can't reproduce it. @Olethros could you please provide some information that I can fill out the submit form?

![filesubmit](https://user-images.githubusercontent.com/1749893/37804496-d25f8114-2e34-11e8-9990-ab59592d341f.png)

Select the Microsoft security product used to scan the file 
- System Center Endpoint Protection
- Windows Defender Antivirus (Windows 10)
- Windows Defender ATP
- Windows Intune
- Microsoft DaRT
- Microsoft Forefront Client Security
- Mircosoft Forefront Endpoint Protection 2010
- Microsoft Forefront Protection for SharePoint
- Microsoft Forefront Server Security
- Microsoft Security Essentials
- Office 365 and Exchange Online Protection
- System Center 2012 Endpoint Protection
- Windows Defender (Windows 8)
- Windows Defender (Windows 7, Windows Vista, or Windows XP)
- Windows SErver Antimalware
- Other

**Comment by Olethros** [comment]
Original submission ID:  9005878b-cde3-4552-9262-34d655fd1e4a
Submission URL: https://www.microsoft.com/en-us/wdsi/submission/9005878b-cde3-4552-9262-34d655fd1e4a
Rescanned today with latest definitions, still detects it as a trojan
Microsoft security product used to scan the file "Windows Defender Antivirus (Windows 10)"
Detection Name: Trojan:Win32/Critet.BS
Definitions: 1.263.1989.0 (April 3. 2018)
Additional Information: 
Downloaded from here https://github.com/zarunbal/LogExpert/releases Prior releases have been OK.

**Comment by David-Patow** [comment]
Could this be a false positive, already resolved?
See: https://forum.kerbalspaceprogram.com/index.php?/topic/172357-trojanwin32critetbs/
There was a false positive reported on a .NET C# DLL, for this same malware, at about the same time.
My current scans with Windows Defender do not flag it.

**Comment by zarunbal** [comment]
My submission doesn't show any detections. @Olethros can you confirm that on your machine this detection is solved?
![2018-05-06 21_31_04-submission details aa8d3900-73cd-4275-a3b9-ab880b2ae31d - windows defender sec](https://user-images.githubusercontent.com/1749893/39677025-daee9e38-5174-11e8-95ae-987773928664.png)

**Comment by zarunbal** [comment]
I assume that this problem is fixed. If there is still a problem please feel free to reopen this issue or create a new one
