### ISSUE TITLE
Previous seleceted line rendering when new line selected

### ISSUE THREAD

**Issue by englishmatt** [zarunbal/LogExpert#5]
When selecting a line, and then selecting a line above, relative to the first, the newly selected line will render the contents of the previous one. [See gif](https://i.gyazo.com/b5f12269cf768c577e160e6a413c84db.gif).

OS: Windows 10.

**Comment by zarunbal** [comment]
@englishmatt does this happen always on the first try or sometime later? Because I have a realy hard time to reliable reproduce this problem.

**Comment by zarunbal** [comment]
@englishmatt is this issue still there in the new release? I made some changes to the log line retrival in the releases, maybe one of them fixed your problem

**Comment by englishmatt** [comment]
Apologies for the tardy response.

Yes, this happens on the first try, and every other. It always operates this way - to the point I thought that perhaps it was a feature I didn't quite understand :)

I will grab the latest release on my workstation and let you know.

**Comment by zarunbal** [comment]
@englishmatt is this still a problem or fixed with the Release?

**Comment by englishmatt** [comment]
This looks fixed. My very preliminary testing does not exhibit the issue described above. Nice!

**Comment by zarunbal** [comment]
Ok thanks for your feedback. I'll close the issue. If the problem appears again feel free to open the Issue again.
