### ISSUE TITLE
Feature request: a regexp columnizer

### ISSUE THREAD

**Issue by ferenczy** [zarunbal/LogExpert#50]
I have a feature request: implement a _Regular expression columnizer_.

For me, the main drawback of columnizers in LogExpert is that you have to set up a dev environment and compile them. And always recompile them when you need to slightly adjust the line format.

The _Regular expression columnizer_ would simply take a regular expression as a user input and apply it to each line of a log file while columnizing it.

I would say such columnizer would be able to replace all other columnizers and mainly allow the user to quickly completely change the line format.

**Comment by zarunbal** [comment]
There is already a Pull Request from fremag #48 which implements a Regex Columnizer.

Where I must contradict to your statement about Regex would replace all columnizers. For a user that is capable to write a Regex this is true but not everyone is able to write a regex. On the other hand there is some specialized columnizers for xml or json which in my opinion nobody really wants to write a regex to dynamically parse xml / json.

**Comment by ferenczy** [comment]
That's great, I noticed it just made it into the latest release! Thank you.

By replacing all columnizers I didn't mean to remove all existing columnizers and have only the regexp one. I meant that majority of columnizers (e.g. timestamp, CSV, etc.) might be implemented using the regexp columnizer. It would also allow the user to make changes into such columnizers without the need to recompile it if he need it.

But you're right that it would be more than painful to implement such complex parsers as XML or JSON using a regexp. I just didn't realize anyone would have a log in such format.

Anyway, thank you, I'm going to test the regexp columnizer!

**Comment by zarunbal** [comment]
I close this issue because there is a regex columnizer in the release. If there are any problems with the columnizers feel free to create a new issue.
