### ISSUE TITLE
Bug: Persistence file location\ Own directoy is cut if folder contains blanks

### ISSUE THREAD

**Issue by pstein** [zarunbal/LogExpert#51]
When I select in settings---Persistence----Own directory 

a folder which contains blanks then the path is cut in display:

Example:

D:\tools\logfile 2018\ ----> D:\tools\logfile

Pls fix.

Furthermore I miss an option here to specify a relative path to the installation directory.

I want to specify a target folder which is a brother of the logexpert installation folder with the relative path definition "..\mylogs\ (mind the leading double dots)

Could you add this in the next release?

**Comment by zarunbal** [comment]
@pstein thanks for your Bug report. Could you please move your feature request to a new issue so the status can be easier tracked.

**Comment by Hirogen** [comment]
Hi this problem seems to be fixed in 1.6.13

https://imgur.com/a/XNdcEGQ

**Comment by zarunbal** [comment]
Seems to be fixed and no feedback, I'll close the issue. If there is still a problem feel free to reopen this issue
