### ISSUE TITLE
Json with diffrent columns on diffrent lines?

### ISSUE THREAD

**Issue by Peter-Optiway** [zarunbal/LogExpert#59]
I'm using NLog structured logging and it dynamically generates fields on each row.
But when using the `JSON columnizer` it only shows the columns on the first row, is there any way to add a setting to search each row for fields?

example:
```json
{ "time": "2018-04-05 13:42:50.6259", "level": "INFO", "thread": "10 Initial", "message": "Topshelf v4.0.0.0, .NET Framework v4.0.30319.42000" }
{ "time": "2018-04-05 13:42:50.8719", "level": "WARN", "thread": "10 Initial", "message": "test", "exception": "System.Exception: Exception of type 'System.Exception' was thrown." }
{ "time": "2018-04-05 14:31:22.1506", "level": "INFO", "thread": "19 ", "message": "Request received (\"DB\", \"GetOne\")", "module": "DB", "method": "GetOne" }
{ "time": "2018-04-05 14:31:22.1856", "level": "INFO", "thread": "13 ", "message": "It took 4,0803 msec to buffer \"pin\"", "elapsedMilliseconds": 4.0803, "name": "pin" }
{ "time": "2018-04-05 14:31:22.7596", "level": "INFO", "thread": "19 ", "message": "Request received (\"DB\", \"Count\")", "module": "DB", "method": "Count" }
```

**Comment by zarunbal** [comment]
Somehow this is possible but the important part is that the columns are more or less static. You can't change them always (If you reload the file then the columns get recreated, but this costs performance). It would be possible to check from the columnizer if there are new fields and add them to a overflow column which then displays every not recognized field.

But this behavior has to be implemented in the columnizer.

**Comment by Peter-Optiway** [comment]
Most of stay the same, only a few of them change.

**Comment by s-tarasov** [comment]
Looks like already implemented?!

**Comment by Hirogen** [comment]
This is already implemented!

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/8225398/179359383-6666fb13-5b2e-4a0a-989b-c5600cabf6ef.png">
