### ISSUE TITLE
CSV Columnizer Missing

### ISSUE THREAD

**Issue by tstreibl** [zarunbal/LogExpert#6]
Hello,

first of all thanks a lot for upgrading this super tool to .NET 4.0. 

Compared to the previous version the SV Columnizer seems to be missing in the Options-> Columnizer Menue. I'm not good at regex so it would be glad it you could bring back this feature.

Would be extreamly happy if those two issues could be fixed.

Edit [Zarunbal]: moved the encoding issue to #7

**Comment by zarunbal** [comment]
@tstreibl please only one issue per "Github Issue" so it can be tracked easier. I was so free and splitted this issue. #7

**Comment by tstreibl** [comment]
Thanks for the fast update to version 1.6.3. Columnizer now shows up-great. 

Unfortunately it doesn't work as expected jet. For the attached log file I get with the default settings empty columns and (sometimes) the attached error.
[log_example.log](https://github.com/zarunbal/LogExpert/files/1435241/log_example.log)
[errorlog.txt](https://github.com/zarunbal/LogExpert/files/1435242/errorlog.txt)

**Comment by zarunbal** [comment]
Found and fixed the NullReference Exception what you are getting if you open the about dialog.

@tstreibl I can't replicate your behavior with the provided files, that you are getting empty columns. Could you please check following points
- What is the "default setting"
- Are there any lines (try to click where normaly the log file would be displayed)
- Check the **Options -> Hilighting and triggers...** if there are "faulty" hilightings like white foreground and background color
- What columnizer is displayed when you open **Options -> Columnizer...**

**Comment by zarunbal** [comment]
hmm there are some automatics in Github ... I reopened the issue.

**Comment by tstreibl** [comment]
@zarunbal Here are some screen shots which hopefully can anser your questions. Testet on a Win 10 Home Edition, build 1703,64bit Machine. Deletet all Highliting before:
![step 1](https://user-images.githubusercontent.com/32412085/32322347-8cdfdd0c-bfc4-11e7-83b3-fa79584fac7d.jpg)
![step 2](https://user-images.githubusercontent.com/32412085/32322363-98159b4e-bfc4-11e7-8de7-8c7c6866ad76.jpg)
![step 3](https://user-images.githubusercontent.com/32412085/32322368-9e428888-bfc4-11e7-9885-8ff90095b1a4.jpg)
![step 4](https://user-images.githubusercontent.com/32412085/32322374-a3b3f086-bfc4-11e7-8a5b-d4b67366e62b.jpg)
![step 5](https://user-images.githubusercontent.com/32412085/32322379-a91d155c-bfc4-11e7-90e4-9b0e97acc0a7.jpg)

Had the chance to test it on a second system (Win10 professional 64 bit in a virtual machine) as well. Same picture.

**Comment by zarunbal** [comment]
@tstreibl  Thanks for the Screenshots, with these I found the Problem.

Created a new Release which fixes your problems.

**Comment by tstreibl** [comment]
@zarunbal Now everthing works like a charm. Thanks a lot!
