### ISSUE TITLE
Sending email

### ISSUE THREAD

**Issue by DavidS77** [zarunbal/LogExpert#60]
I'm newbie here so, please, excuse me for my question (and my English too). I want to send an email when LogExpert find a match with predetermined pattern. Is it possible? I can use WindowsPowerShell as program for sending an email through command line command but i don't know how can i do it. Can you help me with my issue, if it's possible? Thanks in advance.

**Comment by Hirogen** [comment]
I dont think this is currently possible, you want to send an email if the "text-filter" / "filter" (F4) finds a match?

**Comment by DavidS77** [comment]
>  you want to send an email if the "text-filter" / "filter" (F4) finds a match?

Yep! You absolutely correct. This is it what i want.

**Comment by zarunbal** [comment]
Welcome here! I think your idea is possible, if you have something that is executable to send the email. 

You have to configure a "highlighting" that has a trigger. 
- Options
- Highlighting and triggers...
- there you have to configure your keyword (Its possible to use Regex)
- Check the Plugin checkbox
- Click on select
- Select the "ProcessLauncher keyword plugin"
- Put the path to the executable and if needed further parameters in Parameter textbox.
- Close the "Keyword Action" Dialog with ok
- Click the "Add" button
- Close the "Hilighting and action triggers" dialog with ok.
- Wait till the search string matches and executes your executable

![grafik](https://user-images.githubusercontent.com/1749893/39783152-741144e4-5314-11e8-9422-c95d954abd10.png)

If there are still questions feel free to ask.

**Comment by DavidS77** [comment]
> Thanks a lot! It works!

> I've used Windows PowerShell (built-in Windows program) for sending email via Gmail using command:

powershell.exe -ExecutionPolicy ByPass -File c:\folder1\email\MyScript.ps1

> The script you can write in Notepad (using file extention .ps1):

$email = "MyMailBox@gmail.com"
$emailto = "SendToEmailBox@MailServer.com"

$pass = "jkl123"
$smtpServer = "smtp.gmail.com"

$msg = new-object Net.Mail.MailMessage
$smtp = new-object Net.Mail.SmtpClient($smtpServer)
$smtp.EnableSsl = $true
$msg.From = "$email" 
$msg.To.Add("$emailto")

$msg.BodyEncoding = [system.Text.Encoding]::UTF8
$msg.SubjectEncoding = [system.Text.Encoding]::UTF8
$msg.IsBodyHTML = $true 

$msg.Subject = "It's an email Subject field"
$msg.Body = "Your text here"

$SMTP.Credentials = New-Object System.Net.NetworkCredential("$email", "$pass");

$smtp.Send($msg)

**Comment by DavidS77** [comment]
I hope this will help for somebody!

**Comment by zarunbal** [comment]
@DavidS77 Thanks for your feedback and the script. what are meaning with "Update .NET if Win7"?
If this question is not related to the current problem please create a new Issue to keep the conversations on topic.

**Comment by DavidS77** [comment]
> what are meaning with "Update .NET if Win7"?

I just want to say that i use MacOS Sierra and run LogExpert and my scripts under old Windows 7 (really old - 5 years without updates) on virtual PC (Parallels) and when i've used this script for sending email i received my emails with broken encoding (totally unreadable like chinese hieroglyphs). When i've tried to find an answer for this issue in the internet i've found solution on a one forum where one guy was told that Win7 uses first version of the PowerShell and PowerShell uses .Net framework and in this release were some bugs with encoding and he needed to update framework to latest version for solving the problem with encoding. After i've read this post on forum, i've updated my old .Net framework with new release and now i got all my mails with right encoding. Thats why i told about updating .Net framework. If someone receive emails with broken encoding he will be knew that it's not a problem with LogExpert or script - it's problem with old .Net framework and first release of the PowerShell. 

Excuse me for my English... :(

**Comment by zarunbal** [comment]
Create a example wiki page and copied the example there. https://github.com/zarunbal/LogExpert/wiki/Usage-Examples
I'll close this issue. If this topic is still pending feel free to reopen this issue.
