### ISSUE TITLE
How to save all opened tabs?

### ISSUE THREAD

**Issue by DavidS77** [zarunbal/LogExpert#61]
Good day.

I have many filters opened as tabs in my LogExpert. After closing program i have to apply this filters again to open as tabs. Is there any possibility to save all of this tabs (filters)? Because i spend lots of time to re-open of this filters as tabs.

Thanks in advance for your answers.

p.s. excuse me for my English.

**Comment by Pr0metheus2** [comment]
Select from menu **File** / **Save sesion**

Also, if you close program and open it, it will reopen last tabs if you select the following option:
![image](https://user-images.githubusercontent.com/9161285/39853634-a37beabc-5423-11e8-82e7-26f3923865b1.png)

**Comment by Pr0metheus2** [comment]
Read carefully. You have to tick "Re-open last used files".

**Comment by DavidS77** [comment]
> "Re-open last used files".

Checked. Not working.

**Comment by Pr0metheus2** [comment]
Maybe you are not administrator?

**Comment by DavidS77** [comment]
Not only the Administrator, but also LogExpert works with forcibly enabled administrator privileges.

**Comment by DavidS77** [comment]
Anybody here?

**Comment by DavidS77** [comment]
> Do you have under Settings -> Persistence both checkboxes enabled?

Yes, but still doesn't work :-(

> Yes, still here and alive ;) I always try to answer and check problems as fast as I can, but I maintain this project in my free time.

Great thanks!

**Comment by zarunbal** [comment]
I have some actions which I hope one of will work or bring up some error where we can start

1. Are there any logs generated (see [wiki](https://github.com/zarunbal/LogExpert/wiki/FAQ#logging))? Could you please check if there is any error if not change to Debug and execute again LogExpert and then attach them here.
2. Could you just for testing create a "easy" filter to tab which only filter for e.g. 'Test abcde' without Plugins and so on. Does the restore work for this?
3. Another Idea is that you delete the %AppData%\Roaming\LogExpert\ and the Persistence location (default %UserProfile%\Documents\LogExpert\) that everything of LogExpert is reset (Includes Settings). Check again if there is a problem with the restore of. You can backup the folder and later restore them if this point doesn't help.

**Comment by DavidS77** [comment]
I have found one strange thing. I've choosed directory for Persistence location as My Documents and everything was fine, but i've did something (probably, i've pushed Reset button on my PC without closing LogEx, just pushed Reset without "Turn off Windows 7") and the Persistence location was reset to default (as log file location). What i want to say... When Persistence location were at My Docs - tabs are reopends at program start. When Persistence location at log file folder - nothing reopends.

**Comment by zarunbal** [comment]
Ok thanks for the hint, I'll check how the tab recovery works with the different Persistence location.

**Comment by DavidS77** [comment]
I've found the reason. It's in the log-file. If you save filters as tabs and after closing program will delete the log-file - filters will lost, they'll just dissapear.

**Comment by Hirogen** [comment]
so the feature is actually reopen any filter that has been redirected to a new tab?

**Comment by Hirogen** [comment]
As of Version 1.8.7 this works for me.

1. Open Logfile
2. Create Filter
3. Filter to new Tab
4. Close Logexpert
5. Reopen Logexpert
6. All tabs including the filtered one are opend

<img width="696" alt="image" src="https://user-images.githubusercontent.com/8225398/179359672-9bc1d450-b4a0-49ce-aeab-7bdda458c412.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/8225398/179359686-8f40c542-72fe-49f5-ad59-6702be4cd1e9.png">

**Comment by titou10titou10** [comment]
It was not working for me too with v1.12.0.0
Solution? empty the`MyDocument\LogExpert`directory and now it works
