### ISSUE TITLE
Black background in word-mode (hilighting and triggers)

### ISSUE THREAD

**Issue by DavidS77** [zarunbal/LogExpert#66]
I've think it's a #bug.

If you want to use Word-mode in "hilighting and triggers" menu all your screen becames black. Until log file changed. If log file not changed for any reason for a while - you can't see anything.

**Comment by zarunbal** [comment]
@DavidS77 did you use regex or other settings beside "word mode"? Maybe if its possible you could add a screenshot what data you tipped into the "hilighting and triggers" dialog and how the resulting window look.

**Comment by Hirogen** [comment]
See following comment:
https://github.com/zarunbal/LogExpert/issues/40#issuecomment-486709411

Please test again with the latest version 1.6.14

**Comment by Hirogen** [comment]
dpublicated to issue #40
