### ISSUE TITLE
Default Encoding Setting without Effect

### ISSUE THREAD

**Issue by zarunbal** [zarunbal/LogExpert#7]
The Default Encoding set under Tools->Settings->ViewSettings seams to be without effect. At least I cant decode an utf8 log with german "Umlaute" (äöü) correctly. That worked fine before.

Splitted from Issue #6 and user @tstreibl

**Comment by zarunbal** [comment]
The Default Encoding value is only a fallback if the encoding can not be determined from the preamble of the file.
@tstreibl You can override the detected Settings with *View / Navigate -> Encoding* there you see what encoding is currently used and can set it.

**Comment by tstreibl** [comment]
Sorry, I'm stupid. That did the trick. All "Umlaute" are back. Thank's a lot

**Comment by zarunbal** [comment]
No problem, happy to help ;)
