### ISSUE TITLE
Out of range for simple filtering

### ISSUE THREAD

**Issue by DJ-ZX** [zarunbal/LogExpert#76]
Did not encounter same with v1.5 (legacy), reproduced with the latest version from zip

![image](https://user-images.githubusercontent.com/13614247/45037781-08747900-b060-11e8-8029-d97492b6f5f8.png)

**Comment by zarunbal** [comment]
@DJ-ZX thanks for your report. It seems that this is the same problem as #32. Could you please move your message there, to avoid duplications.

**Comment by zarunbal** [comment]
Fixed with this release. If it still persists please reopen the bug
