### ISSUE TITLE
Missing CSV Columnizer

### ISSUE THREAD

**Issue by stefanwendelmann** [zarunbal/LogExpert#8]
Missing CSV Columnizer in Version greater than 

1.5 build 5493

**Comment by zarunbal** [comment]
@stefanwendelmann please use the latest release from GitHub Releases [latest](https://github.com/zarunbal/LogExpert/releases/latest). Or from where you have downloaded the version?

**Comment by stefanwendelmann** [comment]
@zarunbal i used the latest release from GitHub Releases 1.6.4. But the CSV Columnizer is missing in all releases since 1.5 build 5493.

![2017-11-09 11_23_10-logexpert - c__temp_07er kosten e1 ows 07 2016_py csv](https://user-images.githubusercontent.com/3920790/32600689-b7e8742e-c540-11e7-968f-445b4cde3038.png)
![2017-11-09 11_23_33-logexpert - c__temp_07er kosten e1 ows 07 2016_py csv](https://user-images.githubusercontent.com/3920790/32600690-b7fd4700-c540-11e7-86f3-0773f1153b42.png)

**Comment by zarunbal** [comment]
@stefanwendelmann can you check if the Columnizer is present in Options -> Columnizer?

**Comment by stefanwendelmann** [comment]
@zarunbal 

- is the Columnizer present in Options -> Columnizer?
**no**
- Exists a Plugin directory under the LogExpert folder with a CsvColumnizer.dll and LumenWorks.Framework.IO.dll
**yes**

C:.
│   ColumnizerLib.dll
│   CookComputing.XmlRpcV2.dll
│   license.txt
│   LogExpert.exe
│   LogExpert.exe.config
│   Start.cmd
│   WeifenLuo.WinFormsUI.Docking.dll
│
└───plugins
        ColumnizerLib.dll
        CsvColumnizer.dll
        DefaultPlugins.dll
        FlashIconHighlighter.dll
        GlassfishColumnizer.dll
        Log4jXmlColumnizer.dll
        LumenWorks.Framework.IO.dll

**Comment by zarunbal** [comment]
@stefanwendelmann Thanks for your informations! I created a new release which includes enhanced logging. Could you please test with enabled Debug Log (see release notes) if the CSV Columnizer is still missing in this release? If the CSV Columnizer is still missing please attach the log file and the Version which is displayed in the Help -> About.

**Comment by stefanwendelmann** [comment]
@zarunbal as u said i set both Log minlevel to Debug as shown in the releaseinfo.
The CSV Columnizer is still missing and i got no log. Even as i start it as Administrator.

This is the contet of the Help-> About.

> Log file viewing for the Pros
>
> Credits:
>
> DockPanel control (c) 2007 Weifen Luo 
> Early bird test: Mathias Dräger
>
> LogExpert uses modules from:
> http://sourceforge.net/projects/dockpanelsuite/
> http://www.xml-rpc.net/

Seems as there is nothing logged :(

**Comment by stefanwendelmann** [comment]
@zarunbal when i look at the config i can see there is another log path in AppData->Roaming->LogExpert->logs

There seems something wrong with the CsvColumnizer.dll

Please see the logfile attached
[logexpert.log](https://github.com/zarunbal/LogExpert/files/1478188/logexpert.log)

**Comment by zarunbal** [comment]
Please copy the attached Logexpert.exe.config to your LogExpert folder and start again LogExpert. Does now the CSV Columnizer show up? But this is mainly a workaround, it activates that even "remote" located assemblies are loaded in full trust.

The main question is why these assemblies are "remote". 
- Have you downloaded the ZIP file with Internet Explorer and unpacked with Windows Explorer?
  - Could you check if the LogExpert.exe or the CsvColumnizer.dll in the properties have a Button to unblock the files?
- Are you using roaming profiles?
- Or some other fancy things like Junction Points to Remote shares or something like this?

[LogExpert.exe.config.zip](https://github.com/zarunbal/LogExpert/files/1484043/LogExpert.exe.config.zip)

**Comment by stefanwendelmann** [comment]
@zarunbal 

It works with your attached config.

I work on my Windows 10 Workstation with Admin rights.

- I Downloaded the Zip with chrome and unzipped it with winrar
-- there is no Lock on any file
- I dont use a roaming profile
- The Files are on my local storage

Please see the Log attached:
[logexpert.log](https://github.com/zarunbal/LogExpert/files/1490470/logexpert.log)

**Comment by Hirogen** [comment]
> It works with your attached config.
> 
> I work on my Windows 10 Workstation with Admin rights.
> 
>     * I Downloaded the Zip with chrome and unzipped it with winrar
>       -- there is no Lock on any file
> 
>     * I dont use a roaming profile
> 
>     * The Files are on my local storage
> 
> 
> Please see the Log attached:

@stefanwendelmann 
Is this still a problem with the current release 1.7.0?

This is the Columunizer Dialog in 1.7.0
![image](https://user-images.githubusercontent.com/8225398/59040649-6a744000-8877-11e9-91ad-bd3deaa26f0a.png)

**Comment by zarunbal** [comment]
A new release is out there, with some fixes which could affect the failing load of plugins. Could you please test if this still happens or is fixed.

A short Feedback would be great if it works for you

**Comment by stefanwendelmann** [comment]
In 1.8.0 i get another error opening a CSV file: 


Invoke oder BeginInvoke kann für ein Steuerelement erst aufgerufen werden, wenn das Fensterhandle erstellt wurde.


InvalidOperationException
   bei System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   bei System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   bei LogExpert.LogWindow.SetCurrentHighlightGroup(String groupName)
   bei LogExpert.LogWindow.LoadFile(String fileName, EncodingOptions encodingOptions)
   bei LogExpert.LogWindow.Reload()
   bei LogExpert.LogWindow.SetColumnizerInternal(ILogLineColumnizer columnizer)
   bei LogExpert.LogWindow.SetColumnizer(ILogLineColumnizer columnizer)
   bei LogExpert.LogWindow..ctor(LogTabWindow parent, String fileName, Boolean isTempFile, Boolean forcePersistenceLoading)
   bei LogExpert.LogTabWindow.AddFileTab(String givenFileName, Boolean isTempFile, String title, Boolean forcePersistenceLoading, ILogLineColumnizer preProcessColumnizer, Boolean doNotAddToDockPanel)
   bei LogExpert.LogTabWindow.LoadFiles(String[] names, Boolean invertLogic)
   bei LogExpert.LogTabWindow.OpenFileDialog()
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by zarunbal** [comment]
@miltob could you please check out this problem. I think this is maybe related to the early selection of the columnizer

**Comment by miltob** [comment]
@zarunbal , I have made some changes to fix this problem. To streamline the whole columnizer related feature may take a while. So I just made a patch for now.

Please also check my comments in the PR here:
https://github.com/zarunbal/LogExpert/pull/126/files#diff-2351ac0d07316f62277284fd489b8246R50

**Comment by ste22g** [comment]
Hi,
with version 1.8.2 the columnizer does not apply the correct formatting to the log file because it does not keep the selection made (in my case CsvColumnizer) if the "automatically save persistence files (.lxp)" option is disabled. In addition it seems that even the file name mask (set in the settings panel) does not work correctly. With version 1.7.1 everything worked correctly.
ste22g

![lxp](https://user-images.githubusercontent.com/20581673/67095522-64dc1e80-f1b6-11e9-916d-950378100549.jpg)

**Comment by kkwaiser** [comment]
For others hitting this error, the fix on my side (centrally managed work machine, Windows 10, LogExpert 1.8.5) was to mark the DLLs as trusted using Microsoft's Streams utility (https://docs.microsoft.com/en-us/sysinternals/downloads/streams).  Basically, in an admin command line session I modified the trust level of the DLLs:

```
> C:\Program Files\Streams\streams.exe -d C:\Program Files\LogExpert\plugins\*.dll
> C:\Program Files\Streams\streams.exe -d C:\Program Files\LogExpert\*.dll
```

**Comment by TerDale** [comment]
Trust can be granted with Windows Explorer: **launch it elevated**, then right-click on a DLL/EXE and check "Unblock" at the bottom of the "General" tab.

**Comment by Hirogen** [comment]
the csv columnizer should no longer be missing, for the other problems please open new issues.
