### ISSUE TITLE
Selected RegEx columnizer not respected when reloading file

### ISSUE THREAD

**Issue by AndisGrossteins** [zarunbal/LogExpert#83]
# Bug
When using a correctly configured RegEx columnizer other than `Regex1Columnizer`, LogExpert switches back to `Regex1Columnizer` during automatic log file refresh with "Follow tail" enabled.
No errors or exceptions are logged while this happens. This is an intermittently updated log file (WordPress debug.log). It's current size is ~550KB, so not much.

Same behavior can be observed when relaunching LogExpert with previously opened files, so this might be caused by how settings are saved and reloaded.

### Steps to reproduce

1. Open a log file which is updated periodically
1. Configure a RegEx columnizer Regex(N>1)Columnizer
1. Enable tail follow mode
1. Wait for the log file to be written to and refreshed by LogExpert

### Expected behavior
LogExpert keeps using the selected RegEx columnizer

### Actual behavior
LogExpert switches to `Regex1Columnizer` and fails to parse the current open logfile because that columnizer isn't configured to parse dates in square brackets.

## Important questions
- LogExpert Version: 1.6.13
- Windows Version: 10 (1803 build 10.0.17134.345)
- Local file
- Used Columnizer: Regex4Columnizer `\[(?<date>\d+-[\w\d]+-\d+)\s+(?<time>\d{2}:\d{2}:\d{2} \w+)\]\s+(?<text>.*)` for PHP error logs
- This must be a new issue since the Regex columnizers were introduced in 1.6.13 RC 1

**Side note:** I'd like to take a look at the LogExpert C# code to see if I can write a PR but I don't have any free time to do that. Ping me on this issue in a few weeks or so and I'll try to help.

**Comment by zarunbal** [comment]
Thanks for this error report. This is interesting, maybe there is a confusion in the persistence or somewhere in this region that only the base class is used and not the Regex1...x.
@AndisGrossteins I appreciate any help I can get

**Comment by zarunbal** [comment]
This is fixed in the new release. If you still encounter athe problem feel free to reopen the issue
