### ISSUE TITLE
How can I make an optional named group with Regex Columnizer?

### ISSUE THREAD

**Issue by Neo791** [zarunbal/LogExpert#86]
I want to catch strings in named groups. the second string is optional. If this optional string is missing my regex code not working.

`(?<entry1>string1) (?<entry2>string2)? (?<entry3>string3)`

How can I make the second string optional?

**Comment by zarunbal** [comment]
I think the problem is that you have if the second group is not there a double white space which doesn't match your string

I think with this change it should work
`(?<entry1>string1) (?<entry2>string2)? ?(?<entry3>string3)`

Please give a short feedback if this helped you.
