### ISSUE TITLE
Only one running instance?

### ISSUE THREAD

**Issue by pphunor** [zarunbal/LogExpert#87]
Whenever I double click on a log file in Windows Explorer a new instance of LogExpert is started to open the file instead of opening a new tab in the running instance. I did not find any setting to change this behavior. Is there any way to get a single LogExpert app running with multiple tabs in such cases? Thanks in advance.
LogExpert 1.16.13
Windows Server 2012 R2

**Comment by zarunbal** [comment]
The desired behavior you can achieve by enable in settings "Allow only 1 window"

![pic01](https://user-images.githubusercontent.com/1749893/51100893-754f0b00-17d8-11e9-8662-e90c7f0991aa.png)
![2019-01-14 08_44_14-settings](https://user-images.githubusercontent.com/1749893/51100925-a4fe1300-17d8-11e9-9395-10538418a60b.png)

Please give a short feedback if this helps you

**Comment by pphunor** [comment]
Yes, it works now, thanks. Perhaps when I tested this option there were multiple instances running, and my changes were ignored/overwritten.
