### ISSUE TITLE
Feature Request: persist highligh settings

### ISSUE THREAD

**Issue by crashinc99** [zarunbal/LogExpert#90]
I set a bunch of colors corresponding to the various log levels [ERROR], [WARN].  After relaunching LogExpert the highlight settings do not persist.

 I can save a session and reload the session to get the highlight colors but have to reload the session to get the colors to activate again.  

I may have missed a way to do this.  Is there a way to launch LogExpert from the command line and specify a session file?  I tried to execute LogExpert.exe -help/-h/-?  but no command line help is provided.  I couldn't find anything in the documentation either.

Thanks.

**Comment by Hirogen** [comment]
Which Version do you use?
I use 1.6.13 and all User Highlighting and Triggers are persistent.

**Comment by crashinc99** [comment]
I'm using 1.5.   Thank you for responding. I will upgrade today!Andy

    On Wednesday, February 13, 2019, 2:16:43 AM EST, Patrick Bruner <notifications@github.com> wrote:  
 
 
Which Version do you use?
I use 1.6.13 and all User Highlighting and Triggers are persistent.

**Comment by zarunbal** [comment]
@crashinc99 please give a short feedback if it works for you after you upgrade

@Hirogen Thank you, for the answer! :heart:

**Comment by zarunbal** [comment]
I assume the issue is fixed. If this problem appears again feel free to create a new issue or reopen this one

**Comment by crashinc99** [comment]
Hi ,  Sorry I didn't circle back on this.  Yes, the issue if fixed.  Upgrading did the trick.  Thank you!
